import { ref,sameRef,clone,asArray,unique } from '../core/util.js';
import { register,BF,GY,HAND,LIB,anyColor,colorInput,target,playerTarget,selfSacrifice,selfExile,sacrifice,tapOthers,draw,choose,move,search,etb,upkeep,endStep,landfall,spellCast,mana,optional } from './helpers.js';
import { call,isPermanent,lands,artifacts,unionPermanents,graveTypes,gravePermanentCount,putLands,gyPermission,addLandPlays,attack,anyTarget,damageTo } from './expanded-shared.js';
const station=()=>({id:'station',label:'Station — tap another creature to add its power in charge counters',sorcery:true,costs:[tapOthers({...BF,creature:true,another:true},1,'stationed')],effect:()=>[{op:'call',handler:'special.station'}]});
const threshold=(n,layer,apply)=>({layer,match:(g,s,o)=>s.zone==='battlefield'&&sameRef(s,o)&&(s.counters.charge||0)>=n,apply});
const creature=(g,s,o,c)=>{c.types=unique([...c.types,'Creature']);};
const tracked=(color)=>mana({[color]:1},{effect:()=>[{op:'mana',production:{[color]:1},track:true}]});
const paidWith=(s,e)=>e.manaSources?.some(r=>sameRef(s,r));
export function installExpandedSpecial(registry){
 register(registry,'Gretchen Titchwillow',{activated:[{id:'draw-land',label:'Draw a card, then you may put a land from hand into play',cost:'{2}{G}{U}',effect:()=>[draw(),...putLands()]}]});
 register(registry,'Meloku the Clouded Mirror',{activated:[{id:'illusion',label:'Return a land: create a flying Illusion',cost:'{1}',costs:[{kind:'return',key:'land',selector:{...BF,land:true},count:1}],effect:()=>[{op:'token',card:'Illusion'}]}]});
 register(registry,'Patron of the Moon',{offering:'Moonfolk',activated:[{id:'put-lands',label:'Put up to two land cards from hand onto the battlefield tapped',cost:'{1}',effect:()=>putLands(2,{tapped:true})}]});
 register(registry,'Zimone, Quandrix Prodigy',{activated:[{id:'put-land',label:'Put a land from hand into play tapped',cost:'{1}',tap:true,effect:()=>putLands(1,{tapped:true})},{id:'draw',label:'Draw one card, or two if you control eight lands',cost:'{4}',tap:true,effect:(g,c)=>[draw(lands(g,c.controller)>=8?2:1)]}]});
 register(registry,'Zimone and Dina',{triggers:[{id:'second-draw',label:'Your second draw: target opponent loses 2 life and you gain 2',event:'DRAW',test:(g,s,e)=>e.player===s.controller&&(g.state.turnCounts[`draw:${s.controller}:${g.state.turnSerial}:${g.state.activePlayer}`]||0)===2,inputs:[playerTarget('player',true)],effect:(g,c)=>[{op:'life',player:c.inputs.player,amount:-2},{op:'life',amount:2}]}],activated:[{id:'draw-land',label:'Sacrifice another creature: draw and put a land; repeat once with eight lands',tap:true,costs:[sacrifice({...BF,creature:true,another:true})],effect:()=>[draw(),...putLands(1,{tapped:true,key:'zimoneFirstLand'}),call('land-count-gate',{count:8,then:[draw(),...putLands(1,{tapped:true,key:'zimoneSecondLand'})]})]}]});
 register(registry,'Wight of the Reliquary',{characteristics:(g,o,c)=>{if(o.zone==='battlefield'){const n=g.count({...GY,owner:o.controller,creature:true});c.power+=n;c.toughness+=n;}},activated:[{id:'search-land',label:'Sacrifice another creature: find a land and put it into play tapped',tap:true,costs:[sacrifice({...BF,creature:true,another:true})],effect:()=>[search({land:true},'battlefield',{tapped:true})]}]});
 register(registry,'Insidious Fungus',{activated:[{id:'choose',label:'Sacrifice: destroy artifact/enchantment, or draw and put a land',cost:'{2}',costs:[selfSacrifice],inputs:(g,s,c)=>[{key:'mode',type:'option',label:'Choose Fungus’s mode',options:[...(g.count({zones:['battlefield'],artifact:true,target:true},c)?[{value:'artifact',label:'Destroy target artifact'}]:[]),...(g.count({zones:['battlefield'],type:'Enchantment',target:true},c)?[{value:'enchantment',label:'Destroy target enchantment'}]:[]),{value:'land',label:'Draw, then you may put a land from hand into play tapped'}]},...(c.inputs.mode==='artifact'?[target({zones:['battlefield'],artifact:true})]:c.inputs.mode==='enchantment'?[target({zones:['battlefield'],type:'Enchantment'})]:[])],effect:(g,c)=>c.inputs.mode==='land'?[draw(),...putLands(1,{tapped:true})]:[{op:'destroy',ids:'$input.target'}]}]});
 register(registry,'Iron Man, Titan of Innovation',{triggers:[attack('upgrade','Create a Treasure, then you may sacrifice a noncreature artifact to upgrade it',()=>[{op:'token',card:'Treasure'},choose('ironSac','You may sacrifice a noncreature artifact',{...BF,artifact:true,creature:false},0,1),call('iron-upgrade')])]});
 registry.registerHandler('expanded.iron-upgrade',(g,c)=>{const o=g.object(c.vars.ironSac[0]);if(!o)return [];const mv=g.characteristics(o).manaValue,changes=g.moveBatch([{id:ref(o),to:'graveyard',cause:'sacrifice'}],c);return changes.length?[search({artifact:true,manaValue:mv+1},'battlefield',{tapped:true})]:[];});
 register(registry,'Wrenn and Seven',{activated:[
  {id:'reveal',label:'+1: Reveal four; lands to hand, rest to graveyard',loyalty:1,effect:()=>[{op:'look',count:4,key:'wrenn',reveal:true},call('wrenn-cards')]},
  {id:'lands',label:'0: Put any number of lands from hand into play tapped',loyalty:0,effect:()=>putLands(100000,{tapped:true})},
  {id:'treefolk',label:'−3: Create a reaching Treefolk as large as your land count',loyalty:-3,effect:()=>[{op:'token',card:'Treefolk'}]},
  {id:'emblem',label:'−8: Return graveyard permanents to hand; no maximum hand size emblem',loyalty:-8,effect:()=>[{op:'move',selector:{...GY,permanent:true},to:'hand'},{op:'emblem',emblem:{noMaximumHandSize:true,label:'You have no maximum hand size'}}]},
 ]});
 registry.registerHandler('expanded.wrenn-cards',(g,c)=>{const ids=c.vars.wrenn||[],land=ids.filter(id=>g.characteristics(id).types.includes('Land'));return [move(land,'hand'),move(ids.filter(id=>!land.includes(id)),'graveyard')];});
 register(registry,'Uro, Titan of Nature\'s Wrath',{escape:{cost:'{G}{G}{U}{U}',count:5},triggers:[etb('sacrifice','Sacrifice Uro unless it escaped',(g,c)=>g.object(c.source)?.flags.escaped?[]:[{op:'sacrifice',ids:'$source'}]),{id:'draw-land',label:'Gain 3 life, draw, then you may put a land into play',events:['ENTER','ATTACK_DECLARED'],test:(g,s,e)=>e.type==='ENTER'?sameRef(s,e.change.afterRef):sameRef(s,e.object),effect:()=>[{op:'life',amount:3},draw(),...putLands()]}]});
 register(registry,'The Gitrog, Ravenous Ride',{activated:[{id:'saddle',label:'Saddle 1 — tap other creatures with total power at least 1',sorcery:true,saddle:true,costs:[{kind:'tap',key:'saddlers',selector:{...BF,creature:true,another:true,tapped:false},min:1,max:100000,minTotalPower:1}],effect:()=>[call('saddled')]}],triggers:[{id:'ride',label:'You may sacrifice a creature that saddled this Mount; draw and put lands',event:'COMBAT_DAMAGE_DEALT',test:(g,s,e)=>sameRef(s,e.source)&&Number.isInteger(e.player),effect:()=>[call('ride-choice')]}]});
 registry.registerHandler('expanded.saddled',(g,c)=>{const s=g.object(c.source);if(s){s.flags.saddledTurn=g.state.turnSerial;g.record('SADDLED',{object:ref(s)});}return [];});
 registry.registerHandler('expanded.ride-choice',(g,c)=>{const s=g.object(c.source);const candidates=(s?.flags.saddledBy||[]).filter(r=>r.turn===g.state.turnSerial&&g.object(r.ref)?.zone==='battlefield'&&g.object(r.ref).controller===c.controller&&g.characteristics(r.ref.id).types.includes('Creature')).map(r=>r.ref.id);return [{op:'choose',key:'rideSac',label:'You may sacrifice a creature that saddled this Mount this turn',ids:candidates,min:0,max:1},call('ride-sacrifice')];});
 registry.registerHandler('expanded.ride-sacrifice',(g,c)=>{const s=g.object(c.vars.rideSac[0]);if(!s)return [];const power=Math.max(0,g.characteristics(s).power),changes=g.moveBatch([{id:ref(s),to:'graveyard',cause:'sacrifice'}],c);return changes.length?[draw(power),...putLands(power,{tapped:true,key:'rideLands'})]:[];});
 register(registry,'Exploration Broodship',{extraLands:(g,s)=>(s.counters.charge||0)>=3?1:0,activated:[station()],statics:[threshold(8,4,creature),threshold(8,6,(g,s,o,c)=>c.keywords.push('Flying'))],permissions:[{id:'graveyard-permanent',label:'Broodship — once this turn, cast a graveyard permanent and sacrifice a land',zone:'graveyard',land:false,spell:true,oncePerTurn:true,test:(g,s,o)=>s.controller===o.owner&&(s.counters.charge||0)>=8&&g.state.activePlayer===s.controller&&isPermanent(g.characteristics(o)),additionalCosts:[sacrifice({...BF,land:true})]}]});
 register(registry,'Hearthhull, the Worldseed',{activated:[station(),{id:'harvest',label:'Sacrifice a land: draw two and gain an additional land play',cost:'{1}',tap:true,available:(g,s)=>(s.counters.charge||0)>=2,costs:[sacrifice({...BF,land:true})],effect:()=>[draw(2),addLandPlays()]}],statics:[threshold(8,4,creature),threshold(8,6,(g,s,o,c)=>c.keywords.push('Flying','Vigilance','Haste'))],triggers:[{id:'land-drain',label:'Each opponent loses 2 life',event:'SACRIFICED',test:(g,s,e)=>(s.counters.charge||0)>=8&&e.change.lki.controller===s.controller&&e.change.lki.characteristics.types.includes('Land'),effect:(g,c)=>g.state.players.filter(p=>p.id!==c.controller&&!p.lost).map(p=>({op:'life',player:p.id,amount:-2}))}]});
 register(registry,'Eusocial Engineering',{warp:'{1}{G}',triggers:[landfall('robot','Create a Robot artifact creature',()=>[{op:'token',card:'Robot'}])]});
 register(registry,'The Everflowing Well',{triggers:[etb('mill-draw','Mill two, then draw two',()=>[{op:'mill',count:2},draw(2)]),upkeep('descend','Transform with eight permanent cards in your graveyard',()=>[{op:'transform'}],{test:(g,s,e)=>e.player===s.controller&&gravePermanentCount(g,s.controller)>=8,interveningIf:(g,c)=>gravePermanentCount(g,c.controller)>=8})],back:{status:'implemented',keywords:[],possibleMana:['U'],activated:[tracked('U')],triggers:[spellCast('copy-spell','Up to one other permanent becomes a copy of the spell until end of turn',(g,s,e)=>isPermanent(e.characteristics)&&paidWith(s,e),()=>[{op:'temporaryCopy',ids:'$input.target',snapshot:'$event.castSnapshot'}],{inputs:[target({...BF,permanent:true,another:true},'target',0,1)]})]}});
 register(registry,'Thousand Moons Smithy',{triggers:[etb('gnome','Create a Gnome Soldier',()=>[{op:'token',card:'Gnome Soldier'}]),{id:'transform',label:'You may tap five untapped artifacts/creatures to transform Smithy',event:'MAIN_BEGAN',test:(g,s,e)=>e.player===s.controller&&e.precombat,effect:()=>[{op:'choose',key:'smithyTap',label:'Choose five untapped artifacts and/or creatures, or choose none',selector:{...BF,type:['Artifact','Creature'],tapped:false},min:0,max:5,allowedCounts:[0,5]},call('smithy-transform')]}],back:{status:'implemented',keywords:[],possibleMana:['W'],activated:[tracked('W')],triggers:[spellCast('gnome-cast','Create a Gnome Soldier for a spell using this mana',(g,s,e)=>e.characteristics.types.some(t=>['Artifact','Creature'].includes(t))&&paidWith(s,e),()=>[{op:'token',card:'Gnome Soldier'}])]}});
 registry.registerHandler('expanded.smithy-transform',(g,c)=>c.vars.smithyTap.length===5?[{op:'tap',ids:'$var.smithyTap'},{op:'transform'}]:[]);
 register(registry,'Unstable Glyphbridge',{triggers:[etb('destroy','If cast, choose a small creature for each player; destroy the rest',()=>[call('glyph-choose',{player:0})],{test:(g,s,e)=>sameRef(s,e.change.afterRef)&&e.change.object.flags.cast})],activated:[{id:'craft',label:'Craft with an artifact from battlefield or graveyard',cost:'{3}{W}{W}',sorcery:true,costs:[selfExile,{kind:'exile',key:'craftArtifact',selector:{artifact:true,another:true,anyOf:[{zones:['battlefield'],controller:'you'},{zones:['graveyard'],owner:'you'}],zones:['battlefield','graveyard']},count:1}],effect:(g,c)=>[move(c.source.id,'battlefield',{from:'exile',face:1,cause:'craft'})]}],back:{status:'implemented',keywords:['Flying'],canCast:(g,s,o)=>o.owner===s.controller||!g.state.turnCounts[`attacked:${o.owner}:${s.controller}`],attackAllowed:(g,s,o,player)=>player!==s.controller||!g.state.effects.some(e=>e.kind==='glyphAttackStop'&&e.player===o.controller&&e.defender===s.controller),triggers:[{id:'no-attacks',label:'The opponent cannot attack you this turn after casting',event:'SPELL_CAST',test:(g,s,e)=>e.controller!==s.controller&&e.controller===g.state.activePlayer,effect:(g,c)=>[{op:'effect',effect:{kind:'glyphAttackStop',player:c.event.controller,defender:c.controller,expires:'endOfTurn'}}]}]}});
 registry.registerHandler('expanded.glyph-choose',(g,c,cmd)=>{
  const p=cmd.player;if(p>=4){const ids=Object.keys(c.vars).filter(k=>k.startsWith('glyphPlayer')).flatMap(k=>c.vars[k]||[]);return [{op:'destroy',selector:{zones:['battlefield'],creature:true,exclude:ids}}];}
  const candidates=g.select({zones:['battlefield'],controller:p,creature:true,power:{lte:2}},c);
  return [...(candidates.length?[{op:'choose',key:'glyphPlayer'+p,label:`Choose a power 2 or less creature controlled by ${g.state.players[p].name}`,ids:candidates,min:1,max:1}]:[]),call('glyph-choose',{player:p+1})];
 });
 register(registry,'Shifting Woodland',{entersTapped:false,entryTapped:(g,s)=>!g.count({...BF,controller:s.owner,subtype:'Forest'}),activated:[{id:'copy-graveyard',label:'Delirium: become a copy of target graveyard permanent until end of turn',cost:'{2}{G}{G}',available:(g,s)=>graveTypes(g,s.controller)>=4,inputs:[target({...GY,permanent:true})],effect:()=>[{op:'temporaryCopy',ids:'$source',target:'$input.target'}]}]});
 register(registry,'Apex Devastator',{triggers:Array.from({length:4},(_,n)=>({id:'cascade-'+n,label:'Cascade '+(n+1),zone:'stackCards',event:'SPELL_CAST',test:(g,s,e)=>sameRef(s,e.card),effect:()=>[call('cascade',{lessThan:10})]}))});
 register(registry,'Chimil, the Inner Sun',{spellsUncounterable:true,triggers:[endStep('discover','Discover 5',()=>[call('cascade',{discover:5})])]});
 registry.registerHandler('expanded.cascade',(g,c,cmd)=>{
  const library=g.activeLibrary(c.controller);const hit=library.findIndex(id=>!g.characteristics(id).types.includes('Land')&&(cmd.discover!=null?g.characteristics(id).manaValue<=cmd.discover:g.characteristics(id).manaValue<cmd.lessThan));
  const revealed=hit<0?library:library.slice(0,hit+1);const found=hit<0?null:revealed.at(-1);
  const changes=g.moveBatch(revealed.map(id=>({id,to:'exile',cause:cmd.discover!=null?'discover':'cascade'})),c);c.vars.cascadeExiled=changes.filter(v=>v.to==='exile').map(v=>v.afterRef);c.vars.cascadeFound=found?ref(g.object(found)):null;
  if(!found)return [call('cascade-bottom')];
  return [{op:'castChoice',ids:[ref(g.object(found))],method:'free',key:'cascadeCast',label:cmd.discover!=null?'Discover: cast this card without its mana cost, or choose none to put it in hand':'Cascade: you may cast this card without its mana cost'},...(cmd.discover!=null?[call('discover-hand')]:[]),call('cascade-bottom')];
 });
 registry.registerHandler('expanded.discover-hand',(g,c)=>{const o=g.object(c.vars.cascadeFound);return o?.zone==='exile'?[move(ref(o),'hand')]:[];});
 registry.registerHandler('expanded.cascade-bottom',(g,c)=>[{op:'library',ids:c.vars.cascadeExiled.filter(r=>g.object(r)?.zone==='exile'),position:'bottom',random:true}]);
 register(registry,'Hullbreaker Horror',{uncounterable:true,triggers:[spellCast('bounce','You may return an opposing spell or a nonland permanent',()=>true,(g,c)=>c.inputs.mode==='permanent'?[move('$input.target','hand')]:c.inputs.mode==='spell'?[call('return-spell')]:[],{inputs:(g,s,c)=>[{key:'mode',type:'option',label:'Choose up to one Hullbreaker mode',options:[{value:'none',label:'Choose no mode'},...(g.state.stack.some(v=>v.kind==='spell'&&v.controller!==s.controller)?[{value:'spell',label:'Return target spell you do not control'}]:[]),...(g.count({zones:['battlefield'],nonlandPermanent:true,target:true},c)?[{value:'permanent',label:'Return target nonland permanent'}]:[])]},...(c.inputs.mode==='permanent'?[target({zones:['battlefield'],nonlandPermanent:true})]:c.inputs.mode==='spell'?[{key:'target',type:'stackTarget',label:'Target a spell you do not control',spellOnly:true,opponent:true,target:true,min:1,max:1}]:[])]})]});
 registry.registerHandler('expanded.return-spell',(g,c)=>{for(const value of asArray(c.inputs.target)){const id=value.replace(/^stack:/,''),spell=g.state.stack.find(s=>s.id===id);if(!spell||spell.kind!=='spell')continue;g.state.stack=g.state.stack.filter(s=>s!==spell);const o=g.object(spell.source);if(o)g.moveBatch([{id:ref(o),to:'hand',cause:'return-spell'}],c);g.record('SPELL_RETURNED',{stackId:id});}return [];});
 register(registry,'Smothering Tithe',{triggers:[{id:'treasure',label:'Opponent may pay 2; otherwise you create a Treasure',event:'DRAW',test:(g,s,e)=>e.player!==s.controller,effect:(g,c)=>[{op:'opponentPayment',player:c.event.player,mana:'{2}',then:[],else:[{op:'token',card:'Treasure'}]}]}]});
 registry.registerHandler('expanded.warp-exile',(g,c,cmd)=>{const o=g.object(cmd.card);if(o?.zone!=='battlefield')return [];const changes=g.moveBatch([{id:ref(o),to:'exile',cause:'warp-exile'}],c)||[];for(const change of changes)if(change.to==='exile'){const ex=g.object(change.afterRef);ex.flags.warpedExile=true;g.state.effects.push({id:`permission-${g.state.nextId++}`,kind:'permission',zone:'exile',cards:[change.afterRef],controller:ex.owner,method:'normal',afterTurn:g.state.turnSerial,label:'Cast warped card on a later turn'});}return [];});
 // Suspend's upkeep and last-counter abilities function in exile, independently
 // of how the card became exiled with time counters (CR 702.62).
 for(const name of ['Lotus Bloom','Mox Tantalite','Sol Talisman'])register(registry,name,{triggers:[
  {id:'suspend-tick',label:'Remove a time counter',zone:'exile',event:'UPKEEP',test:(g,s,e)=>e.player===s.owner&&(s.counters.time||0)>0,interveningIf:(g,c)=>g.object(c.source)?.zone==='exile'&&(g.object(c.source).counters.time||0)>0,effect:()=>[{op:'counter',type:'time',amount:-1}]},
  {id:'suspend-cast',label:'You may cast the suspended card without its mana cost',zone:'exile',event:'SUSPEND_LAST_REMOVED',test:(g,s,e)=>sameRef(s,e.object),effect:()=>[{op:'suspendCast'}]},
 ]});
}
