import {ref,sameRef,asArray,clone,unique,requireRule} from '../core/util.js';
import {BF,GY,HAND,LIB,anyColor,options,colorInput,draw,move,choose,search,etb,upkeep,endStep,target,selfSacrifice,discardCost,sacrifice,tapOthers,playerTarget,optional,spellCast,mana,xInput} from './helpers.js';
import {registerG as reg,call,token,god,ownPermanent,ownCreature,keywords,creatures,enchants,power,entry,gain,dies,eachEnd,combatHit,equipment,attached,endure} from './gods-shared.js';
const allCreatureSelector={zones:['battlefield'],creature:true};
const destroyAll=()=>[{op:'destroy',selector:allCreatureSelector}];
export function installGodsSpells(r){
 for(const name of ['Day of Judgment','Wrath of God','Damnation','Vanquish the Horde','Supreme Verdict'])reg(r,name,{spell:{effect:destroyAll}});
 reg(r,'Supreme Verdict',{uncounterable:true});
 reg(r,'Vanquish the Horde',{costReduction:g=>creatures(g).length});
 reg(r,'Damn',{spell:{inputs:[target(allCreatureSelector)],effect:()=>[{op:'destroy',ids:'$input.target'}]},alternateCosts:[{id:'overload',label:'Overload — destroy all creatures',cost:'{2}{W}{W}'}],spellModes:{overload:{effect:destroyAll}}});
 reg(r,'Blasphemous Act',{costReduction:g=>creatures(g).length,spell:{effect:(g,c)=>[{op:'godsDamage',packet:creatures(g).map(o=>({target:ref(o),amount:13}))}]}});
 for(const [name,color]of [['Pestilence','B'],['Pyrohemia','R']])reg(r,name,{activated:[{id:'damage-all',cost:'{'+color+'}',label:'Deal 1 damage to each creature and each player',effect:(g,c)=>[{op:'godsDamage',packet:[...creatures(g).map(o=>({target:ref(o),amount:1})),...g.state.players.filter(p=>!p.lost).map(p=>({target:p.id,amount:1}))]}]}],triggers:[eachEnd('empty-battlefield','Sacrifice this enchantment if there are no creatures',()=>[{op:'sacrifice',ids:'$source'}],{test:g=>!creatures(g).length,interveningIf:g=>!creatures(g).length})]});
 for(const [name,tap]of [['Fauna Shaman',true],['Survival of the Fittest',false]])reg(r,name,{activated:[{id:'creature-search',cost:'{G}',tap,costs:[discardCost({...HAND,creature:true})],label:'Discard a creature: search for a creature',effect:()=>[search({creature:true})]}]});
 reg(r,'Dance of the Manse',{spell:{inputs:(g,s,c)=>[...(c.inputs.x!=null?[target({...GY,anyOf:[{artifact:true},{type:'Enchantment',not:{subtype:'Aura'}}],manaValue:{lte:c.inputs.x}},'target',0,c.inputs.x)]:[])],effect:(g,c)=>[move('$input.target','battlefield',{key:'returns',...(c.inputs.x>=6?{modifications:[{addTypes:['Creature'],basePower:4,baseToughness:4,timestamp:g.state.eventSerial+1}]}:{})})]}});
 reg(r,'Relive the Past',{spell:{inputs:[target({...GY,artifact:true},'artifact',0,1),target({...GY,land:true},'land',0,1),target({...GY,type:'Enchantment',not:{subtype:'Aura'}},'enchantment',0,1)],effect:(g,c)=>[move(unique([...asArray(c.inputs.artifact),...asArray(c.inputs.land),...asArray(c.inputs.enchantment)]),'battlefield',{key:'returns',modifications:[{addTypes:['Creature'],addSubtypes:['Elemental'],basePower:5,baseToughness:5,timestamp:g.state.eventSerial+1}]})]}});
 reg(r,'Quicken',{spell:{effect:()=>[{op:'effect',effect:{kind:'quicken',expires:'endOfTurn'}},draw()]}});
 reg(r,'Gravebreaker Lamia',{costModifiers:[{test:(g,s,o)=>o.zone==='graveyard',amount:()=>1}],triggers:[etb('entomb','Search for a card and put it into your graveyard',()=>[search({},'graveyard')])]});
 reg(r,'Arcanist\'s Owl',{triggers:[etb('look-four','Look at four; you may take an artifact or enchantment',()=>[{op:'look',count:4,key:'owlLook'},call('look-select',{look:'owlLook',selector:{type:['Artifact','Enchantment']}}),call('bottom-rest',{look:'owlLook'})])]});
 reg(r,'Attunement',{activated:[{id:'draw-discard',costs:[{kind:'return',self:true}],label:'Return Attunement to hand: draw three, then discard four',effect:()=>[draw(3),choose('discardFour','Discard four cards',HAND,4),{op:'discard',ids:'$var.discardFour'}]}]});
 reg(r,'Greater Good',{activated:[{id:'sac-draw',costs:[sacrifice({...BF,creature:true})],label:'Sacrifice a creature: draw its power, then discard three',effect:(g,c)=>[draw(Math.max(0,c.costs.sacrificed?.[0]?.characteristics.power||0)),choose('discardThree','Discard three cards',HAND,3),{op:'discard',ids:'$var.discardThree'}]}]});
 reg(r,'Khalni Hydra',{coloredReduction:(g,s)=>({G:creatures(g,s.owner).filter(o=>g.characteristics(o).colors.includes('G')).length})});
 reg(r,'Fire Covenant',{spell:{inputs:(g,s,c)=>{
  const specs=[{...xInput,label:'Choose X life to pay',max:Math.max(0,g.state.players[s.owner].life)}];
  if(c.inputs.x==null)return specs;
  specs.push(target(allCreatureSelector,'target',c.inputs.x>0?1:0,c.inputs.x));
  if(c.inputs.target==null)return specs;
  const ids=asArray(c.inputs.target);let left=c.inputs.x;
  ids.forEach((id,i)=>{const key='damage-'+id;specs.push({key,type:'number',label:'Damage to '+g.definition(id).name,min:1,max:left-(ids.length-i-1)});left-=c.inputs[key]||0;});return specs;
 },life:(g,s,c)=>c.inputs.x||0,validate:(g,s,c)=>requireRule(asArray(c.inputs.target).reduce((n,id)=>n+(c.inputs['damage-'+id]||0),0)===c.inputs.x,'Divide all X damage among the chosen creatures.'),effect:(g,c)=>[{op:'godsDamage',packet:asArray(c.inputs.target).map(id=>({target:id,amount:c.inputs['damage-'+id]||0}))}]}});
 reg(r,'Penance',{activated:[{id:'prevent',costs:[{kind:'putLibrary',key:'topCard',selector:HAND,count:1}],label:'Put a hand card on top: prevent the next damage from a red or black source',effect:()=>[call('penance-choice')]}]});
 r.registerHandler('gods.penance-choice',(g,c)=>{
  const ids=g.objects('battlefield').concat(g.objects('stackCards')).filter(o=>g.characteristics(o).colors.some(v=>['B','R'].includes(v))).map(o=>o.id);
  return [{op:'choose',key:'penanceSource',label:'Choose a red or black source (not a target)',ids,min:1,max:1},call('penance-shield')];
 });
 r.registerHandler('gods.penance-shield',(g,c)=>{const o=g.object(c.vars.penanceSource?.[0]);return o?[{op:'effect',effect:{kind:'penance',source:ref(o),expires:'endOfTurn'}}]:[];});
 reg(r,'Whip of Erebos',{statics:[keywords(ownCreature,['Lifelink'])],activated:[{id:'reanimate',cost:'{2}{B}{B}',tap:true,sorcery:true,inputs:[target({...GY,creature:true})],label:'Return a creature with haste; exile it later',effect:()=>[move('$input.target','battlefield',{flags:{whipReturn:true},modifications:[{keywords:['Haste']}],key:'returns'}),call('whip-delay')]}]});
 r.registerHandler('gods.whip-delay',(g,c)=>{const card=c.vars.returns?.[0]?.afterRef;return card?[{op:'delayed',when:'nextEnd',label:'Whip of Erebos — exile the returned creature',program:[move(card,'exile')]}]:[];});
 reg(r,'Liesa, Forgotten Archangel',{exileOpponentDeaths:true,triggers:[{id:'death-return',label:'Return another nontoken creature to hand at the next end step',event:'LEAVE',test:(g,s,e)=>e.change.to==='graveyard'&&e.change.lki.controller===s.controller&&!sameRef(s,e.change.beforeRef)&&!e.change.lki.token&&e.change.lki.characteristics.types.includes('Creature'),effect:(g,c)=>[{op:'delayed',when:'nextEnd',label:'Liesa — return the creature card to its owner’s hand',program:[move(c.event.change.afterRef,'hand',{from:'graveyard'})]}]}]});
 reg(r,'God-Eternal Oketra',{triggers:[spellCast('zombie-warrior','Create a 4/4 Zombie Warrior with vigilance',(g,s,e)=>e.characteristics.types.includes('Creature'),()=>[token('Zombie Warrior')]),{id:'third-library',label:'You may put God-Eternal Oketra third from the top',event:'LEAVE',test:(g,s,e)=>['graveyard','exile'].includes(e.change.to)&&sameRef(s,e.change.beforeRef),optional:true,effect:(g,c)=>[{op:'godsThird',card:c.event.change.afterRef}]}]});
 reg(r,'Thassa, Deep-Dwelling',{...god('U',5),activated:[{id:'tap',cost:'{3}{U}',label:'Tap another target creature',inputs:[target({...allCreatureSelector,another:true})],effect:()=>[{op:'tap',ids:'$input.target'}]}],triggers:[endStep('blink','Exile up to one other creature you control, then return it under your control',()=>[move('$input.target','exile',{key:'exiled'}),call('thassa-return')],{inputs:[target({...BF,creature:true,another:true},'target',0,1)]})]});
 r.registerHandler('gods.thassa-return',(g,c)=>[move((c.vars.exiled||[]).map(x=>x.afterRef),'battlefield',{controller:c.controller})]);
 reg(r,'Thassa, God of the Sea',{...god('U',5),triggers:[upkeep('scry','Scry 1',()=>[{op:'scry',count:1}])],activated:[{id:'unblockable',cost:'{1}{U}',label:'Target creature you control cannot be blocked this turn',inputs:[target({...BF,creature:true})],effect:()=>[{op:'modify',ids:'$input.target',modification:{keywords:['Unblockable']}}]}]});
 reg(r,'Xenagos, God of Revels',{...god(['R','G'],7),triggers:[{id:'combat-power',label:'Another creature gains haste and +X/+X equal to its power',event:'COMBAT_BEGAN',test:(g,s,e)=>e.player===s.controller,inputs:[target({...BF,creature:true,another:true})],effect:(g,c)=>{const t=g.object(c.inputs.target?.[0]),n=t?g.characteristics(t).power:0;return [{op:'modify',ids:'$input.target',modification:{keywords:['Haste'],power:n,toughness:n}}];}}]});
 reg(r,'Karametra, God of Harvests',{...god(['G','W'],7),triggers:[spellCast('forest-plains','You may search for a Forest or Plains and put it in tapped',(g,s,e)=>e.characteristics.types.includes('Creature'),()=>[search({subtype:['Forest','Plains']},'battlefield',{tapped:true})],{optional:true})]});
 reg(r,'Nylea, Keen-Eyed',{...god('G',5),costModifiers:[{test:(g,s,o)=>g.characteristics(o).types.includes('Creature'),amount:()=>1}],activated:[{id:'reveal-top',cost:'{2}{G}',label:'Reveal the top card; creature to hand, otherwise may mill it',effect:()=>[{op:'look',count:1,reveal:true,key:'nyleaLook'},call('nylea-reveal')]}]});
 r.registerHandler('gods.nylea-reveal',(g,c)=>{const top=g.object(c.vars.nyleaLook?.[0]);if(!top)return [];return g.characteristics(top).types.includes('Creature')?[move(ref(top),'hand')]:[optional('nylea-mill','Put the revealed card into your graveyard?',[move(ref(top),'graveyard')])];});
 const oketraReady=(g,s)=>creatures(g,s.controller).filter(o=>!sameRef(o,s)).length>=3;
 reg(r,'Oketra the True',{canAttack:oketraReady,canBlock:oketraReady,activated:[{id:'warrior',cost:'{3}{W}',label:'Create a 1/1 white Warrior with vigilance',effect:()=>[token('Warrior')]}]});
 reg(r,'Master of Waves',{protectionColors:['red'],statics:[power((g,s,o,c)=>ownCreature(g,s,o,c)&&c.subtypes.includes('Elemental'),1)],triggers:[etb('elementals','Create 1/0 Elementals equal to your devotion to blue',(g,c)=>[token('Elemental',{count:g.devotion(c.controller,'U'),power:1,toughness:0,colors:['U'],keywords:[]})])]});
 reg(r,'Overbeing of Myth',{cda:(g,s,c)=>{c.power=c.toughness=s.controller===0?g.objects('hand',s.controller).length:g.state.players[s.controller].abstractHand;},triggers:[{id:'draw-extra',label:'Draw an additional card',event:'DRAW_STEP',test:(g,s,e)=>e.player===s.controller,effect:()=>[draw()]}]});
 reg(r,'Aclazotz, Deepest Betrayal',{triggers:[{id:'attack-discard',label:'Opponents discard; draw for each who cannot',event:'ATTACK_DECLARED',test:(g,s,e)=>sameRef(s,e.object),effect:(g,c)=>g.state.players.filter(p=>p.id!==c.controller&&!p.lost).map(p=>call('aclazotz-discard',{player:p.id}))},{id:'land-discard',label:'Create a Bat for an opponent’s discarded land',event:'DISCARDED',test:(g,s,e)=>e.change.lki.owner!==s.controller&&e.change.lki.characteristics.types.includes('Land'),effect:()=>[token('Bat')]},{id:'abstract-land-discard',label:'Create a Bat for an opponent’s reported land discard',event:'GODS_ABSTRACT_DISCARD',test:(g,s,e)=>e.player!==s.controller&&e.land,effect:()=>[token('Bat')]},dies('return-transformed','Return Aclazotz tapped and transformed',(g,c)=>[move(c.event.change.afterRef,'battlefield',{controller:c.event.change.lki.owner,tapped:true,face:1})])],back:{status:'implemented',keywords:[],activated:[mana({B:1}),{id:'transform',cost:'{2}{B}',tap:true,sorcery:true,label:'Transform if any player has at most one card in hand',available:g=>g.state.players.some(p=>(p.id===0?g.objects('hand',0).length:p.abstractHand)<=1),effect:()=>[{op:'transform'}]}]}});
 r.registerHandler('gods.aclazotz-discard',(g,c,cmd)=>{
  const p=cmd.player,actual=g.objects('hand',p);
  if(actual.length)return [choose('opponentDiscard'+p,g.state.players[p].name+' chooses a card to discard',{zones:['hand'],owner:p},1),{op:'discard',ids:'$var.opponentDiscard'+p}];
  if(g.state.players[p].abstractHand<=0)return [draw()];
  return [{op:'choose',key:'discardType'+p,label:g.state.players[p].name+' — report discarded card type (abstract opponent)',options:[{value:'nonland',label:'Discard a nonland card'},{value:'land',label:'Discard a land card'}]},call('abstract-discard',{player:p,key:'discardType'+p})];
 });
 r.registerHandler('gods.abstract-discard',(g,c,cmd)=>{g.state.players[cmd.player].abstractHand=Math.max(0,g.state.players[cmd.player].abstractHand-1);g.emit('GODS_ABSTRACT_DISCARD',{player:cmd.player,land:c.vars[cmd.key]==='land'});return [];});
}
