import {ref,sameRef,asArray,clone,unique,requireRule} from '../core/util.js';
import {BF,GY,HAND,LIB,anyColor,options,colorInput,draw,move,choose,search,etb,upkeep,endStep,target,selfSacrifice,discardCost,sacrifice,tapOthers,playerTarget,optional,spellCast,mana} from './helpers.js';
import {registerG as reg,call,token,god,ownPermanent,ownCreature,keywords,creatures,enchants,power,entry,gain,dies,eachEnd,combatHit,equipment,attached,endure} from './gods-shared.js';
const self=(g,s,o)=>sameRef(s,o);
const restoreSelector=(g,c)=>({...GY,owner:c.controller,creature:true,manaValue:{lte:g.lifeGained(c.controller)}});
export function installGodsLife(r){
 reg(r,'Heliod, Sun-Crowned',{...god('W',5),activated:[{id:'lifelink',cost:'{1}{W}',label:'Another creature gains lifelink',inputs:[target({zones:['battlefield'],creature:true,another:true})],effect:()=>[{op:'modify',ids:'$input.target',modification:{keywords:['Lifelink']}}]}],triggers:[gain('life-counter','Put a counter on a creature or enchantment you control',()=>[{op:'counter',ids:'$input.target',type:'+1/+1',amount:1}],{inputs:[target({...BF,type:['Creature','Enchantment']})]})]});
 reg(r,'Daxos, Blessed by the Sun',{cda:(g,s,c)=>{c.toughness=g.devotion(s.controller,'W');},triggers:[entry('enter-life','Gain 1 life for another entering creature','Creature',()=>[{op:'life',amount:1}],{test:(g,s,e)=>e.change.object.controller===s.controller&&e.change.object.characteristics.types.includes('Creature')&&!sameRef(s,e.change.afterRef)}),{id:'die-life',label:'Gain 1 life for another dying creature',event:'LEAVE',test:(g,s,e)=>e.change.to==='graveyard'&&e.change.lki.controller===s.controller&&e.change.lki.characteristics.types.includes('Creature')&&!sameRef(s,e.change.beforeRef),effect:()=>[{op:'life',amount:1}]}]});
 reg(r,'Archangel of Thune',{triggers:[gain('life-counters','Put a +1/+1 counter on each creature you control',(g,c)=>[{op:'counter',ids:creatures(g,c.controller).map(ref),type:'+1/+1',amount:1}])]});
 reg(r,'Drogskol Reaver',{triggers:[gain('life-draw','Draw a card',()=>[draw()])]});
 reg(r,'Nykthos Paragon',{triggers:[gain('life-team','You may put that many counters on your creatures (once per turn)',(g,c)=>{
  const counters={op:'counter',selector:{...BF,creature:true},type:'+1/+1',amount:c.event.amount};
  return [call('if-unused',{key:'paragon',then:[optional('paragon','Put '+c.event.amount+' counters on each creature you control?',[call('once',{key:'paragon',then:[counters]})]) ]})];
 })]});
 reg(r,'Rodolf Duskbringer',{triggers:[gain('indestructible','Rodolf gains indestructible this turn',()=>[{op:'modify',ids:'$source',modification:{keywords:['Indestructible']}}]),endStep('reanimate','You may pay {1}{W/B}; when you do, reanimate a creature',()=>[optional('rodolf-pay','Pay {1}{W/B} to return a creature?',[{op:'choose',key:'rodolfColor',label:'Pay the hybrid symbol with white or black',options:options(['W','B'])},call('rodolf-pay')])])]});
 r.registerHandler('gods.rodolf-pay',(g,c)=>[{op:'pay',mana:`{1}{${c.vars.rodolfColor}}`,then:[call('rodolf-reflexive')]}]);
 r.registerHandler('gods.rodolf-reflexive',(g,c)=>[{op:'godsTrigger',id:'rodolf-reflexive',label:'Rodolf — return target creature within life gained',inputs:[target(restoreSelector(g,c))],program:[move('$input.target','battlefield')]}]);
 reg(r,'Celestine, the Living Saint',{triggers:[endStep('healing-tears','Return target creature within life gained',()=>[move('$input.target','battlefield')],{inputs:(g,s,c)=>[target(restoreSelector(g,c))]})]});
 reg(r,'Enduring Tenacity',{triggers:[endure,gain('opponent-life','Target opponent loses that much life',(g,c)=>[{op:'life',player:c.inputs.player,amount:-c.event.amount}],{inputs:[playerTarget('player',true)]})]});
 reg(r,'Erebos, God of the Dead',{...god('B',5),opponentsCantGainLife:true,activated:[{id:'draw',cost:'{1}{B}',life:2,label:'Pay 2 life: draw a card',effect:()=>[draw()]}]});
 for(const [name,amount,vigilance,horse]of [['Crested Sunmare',1,false,true],['Angelic Accord',4,false,false],['Valkyrie Harbinger',4,true,false],['Resplendent Angel',5,true,false]])reg(r,name,{triggers:[eachEnd('end-life-token',`Create a ${horse?'Horse':'4/4 Angel'} if you gained ${amount} life this turn`,()=>[token(horse?'Horse':'Angel',{keywords:horse?[]:vigilance?['Flying','Vigilance']:['Flying']})],{test:(g,s)=>g.lifeGained(s.controller)>=amount,interveningIf:(g,c)=>g.lifeGained(c.controller)>=amount})]});
 reg(r,'Crested Sunmare',{statics:[keywords((g,s,o,c)=>ownPermanent(g,s,o)&&!sameRef(s,o)&&c.subtypes.includes('Horse'),['Indestructible'])]});
 reg(r,'Resplendent Angel',{activated:[{id:'pump',cost:'{3}{W}{W}{W}',label:'Get +2/+2 and lifelink until end of turn',effect:()=>[{op:'modify',ids:'$source',modification:{power:2,toughness:2,keywords:['Lifelink']}}]}]});
 reg(r,"Archon of Sun's Grace",{statics:[keywords((g,s,o,c)=>ownCreature(g,s,o,c)&&c.subtypes.includes('Pegasus'),['Lifelink'])],triggers:[entry('pegasus','Create a 2/2 flying Pegasus','Enchantment',()=>[token('Pegasus')])]});
 reg(r,'Serra Ascendant',{statics:[power((g,s,o)=>sameRef(s,o)&&g.state.players[s.controller].life>=30,5),keywords((g,s,o)=>sameRef(s,o)&&g.state.players[s.controller].life>=30,['Flying'])]});
 reg(r,'Divinity of Pride',{statics:[power((g,s,o)=>sameRef(s,o)&&g.state.players[s.controller].life>=25,4)]});
 reg(r,'Shadowspear',{activated:[equipment('{2}'),{id:'strip-protection',cost:'{1}',label:'Opposing permanents lose hexproof and indestructible this turn',effect:(g,c)=>[{op:'modify',ids:g.objects('battlefield').filter(o=>o.controller!==c.controller).map(ref),modification:{removeKeywords:['Hexproof','Indestructible']}}]}],statics:[keywords(attached,['Trample','Lifelink']),power(attached,1)]});
 const caduceus=(g,s,o)=>attached(g,s,o)&&g.state.players[s.controller].life>=30;
 reg(r,'Caduceus, Staff of Hermes',{activated:[equipment('{W}{W}')],statics:[keywords(attached,['Lifelink']),power(caduceus,5),keywords(caduceus,['Indestructible']),{layer:6,match:caduceus,apply:(g,s,o,c)=>{c.preventAllDamage=true;}}]});
 reg(r,'Amalia Benavides Aguirre',{triggers:[gain('explore','Explore, then destroy other creatures if power is exactly 20',()=>[{op:'explore'},call('amalia-wipe')]),{id:'ward',label:'Ward — pay 3 life',event:'BECOMES_TARGET',test:(g,s,e)=>sameRef(s,e.target)&&e.controller!==s.controller,effect:()=>[call('ward-life')]}]});
 r.registerHandler('gods.amalia-wipe',(g,c)=>{const o=g.object(c.source);return o?.zone==='battlefield'&&g.characteristics(o).power===20?[{op:'destroy',ids:creatures(g).filter(x=>!sameRef(x,o)).map(ref)}]:[];});
 reg(r,'Well of Lost Dreams',{triggers:[gain('pay-draw','You may pay up to the life gained to draw cards',(g,c)=>[
  optional('well-pay','Pay mana to draw cards?',[{op:'godsNumber',key:'wellX',label:'How much mana? (up to '+c.event.amount+')',min:0,max:c.event.amount},call('well-pay')])
 ])]});
 r.registerHandler('gods.well-pay',(g,c)=>[{op:'pay',mana:'{'+c.vars.wellX+'}',then:[draw(c.vars.wellX)]}]);
 reg(r,'Veinwitch Coven',{triggers:[gain('return-creature','You may pay {B} to return target creature to hand',()=>[{op:'pay',mana:'{B}',then:[move('$input.target','hand')]}],{inputs:[target({...GY,creature:true})]})]});
 reg(r,'Cleric Class',{lifeGainBonus:1,activated:[{id:'level-2',cost:'{3}{W}',sorcery:true,label:'Level 2 — add the lifegain counter ability',available:(g,s)=>(s.flags.classLevel||1)===1,effect:()=>[call('mark',{key:'classLevel',value:2})]},{id:'level-3',cost:'{4}{W}',sorcery:true,label:'Level 3 — return a creature and gain life',available:(g,s)=>s.flags.classLevel===2,effect:()=>[call('mark',{key:'classLevel',value:3})]}],triggers:[gain('class-counters','Put a counter on a creature you control',()=>[{op:'counter',ids:'$input.target',type:'+1/+1',amount:1}],{test:(g,s,e)=>e.player===s.controller&&e.amount>0&&(s.flags.classLevel||1)>=2,inputs:[target({...BF,creature:true})]}),{id:'class-return',label:'Return target creature, then gain life equal to its toughness',event:'GODS_MARK_CHANGED',test:(g,s,e)=>sameRef(s,e.object)&&e.key==='classLevel'&&e.value===3,inputs:[target({...GY,creature:true})],effect:()=>[move('$input.target','battlefield',{key:'returns'}),call('class-life')]}]});
 r.registerHandler('gods.class-life',(g,c)=>{const o=g.object(c.vars.returns?.[0]?.afterRef);return o?[{op:'life',amount:Math.max(0,g.characteristics(o).toughness)}]:[];});
}
