import {installGodsShared} from './gods-shared.js';
import {installGodsMana} from './gods-mana.js';
import {installGodsEnchantments} from './gods-enchantments.js';
import {installGodsLife} from './gods-life.js';
import {installGodsSpells} from './gods-spells.js';
export const GODS_POOL=[
 "Starfield of Nyx",
 "Setessan Champion",
 "Damn",
 "Fauna Shaman",
 "Odric, Lunarch Marshal",
 "Blasphemous Act",
 "Heliod, Sun-Crowned",
 "Jodah, the Unifier",
 "Avacyn, Angel of Hope",
 "Daxos, Blessed by the Sun",
 "Eidolon of Blossoms",
 "Vanquish the Horde",
 "Thassa, Deep-Dwelling",
 "Zur, Eternal Schemer",
 "Day of Judgment",
 "Zur the Enchanter",
 "Altar of the Pantheon",
 "Wrath of God",
 "Eldrazi Monument",
 "Crested Sunmare",
 "Archon of Sun's Grace",
 "Kestia, the Cultivator",
 "Dance of the Manse",
 "Search for Azcanta",
 "Sythis, Harvest's Hand",
 "Xenagos, God of Revels",
 "Nyx Lotus",
 "Bello, Bard of the Brambles",
 "Archangel of Thune",
 "Survival of the Fittest",
 "Kruphix, God of Horizons",
 "Erebos, God of the Dead",
 "Sanctum Weaver",
 "Nylea, Keen-Eyed",
 "Opalescence",
 "Calix, Guided by Fate",
 "Supreme Verdict",
 "Divinity of Pride",
 "Nyxbloom Ancient",
 "Damnation",
 "Rodolf Duskbringer",
 "Fertile Ground",
 "Drogskol Reaver",
 "God-Eternal Oketra",
 "Pestilence",
 "Black Market Connections",
 "Faeburrow Elder",
 "Celestine, the Living Saint",
 "Wild Growth",
 "Nykthos Paragon",
 "Thassa, God of the Sea",
 "True Conviction",
 "Shadowspear",
 "Scroll Rack",
 "Amalia Benavides Aguirre",
 "Timeless Lotus",
 "Smothering Tithe",
 "Pyrohemia",
 "Leyline of Anticipation",
 "Angelic Accord",
 "Herald of the Pantheon",
 "Bloom Tender",
 "Valkyrie Harbinger",
 "Caduceus, Staff of Hermes",
 "Sultai Ascendancy",
 "Oketra the True",
 "Quicken",
 "Wolfwillow Haven",
 "Enduring Tenacity",
 "Carpet of Flowers",
 "Chromatic Orrery",
 "Liesa, Forgotten Archangel",
 "Enduring Vitality",
 "Serra Ascendant",
 "Elven Chorus",
 "Enduring Curiosity",
 "Enduring Courage",
 "Aclazotz, Deepest Betrayal",
 "Nykthos, Shrine to Nyx",
 "City of Brass",
 "Tarnished Citadel",
 "Public Thoroughfare",
 "The World Tree",
 "Grand Coliseum",
 "Plaza of Heroes",
 "Path of Ancestry",
 "Starting Town",
 "Command Tower",
 "Holdout Settlement",
 "Archway Commons",
 "Survivors' Encampment",
 "Forbidden Orchard",
 "Transguild Promenade",
 "Rupture Spire",
 "Crystal Quarry",
 "Mirrodin's Core",
 "Exotic Orchard",
 "Serra's Sanctum",
 "Scene of the Crime",
 "Abundant Countryside",
 "Command Bridge",
 "Gateway Plaza",
 "Mana Confluence",
 "Valgavoth's Lair",
 "Hidden Hideout",
 "Cascading Cataracts",
 "Esika, God of the Tree",
 "Relive the Past",
 "Whip of Erebos",
 "Tuvasa the Sunlit",
 "Karametra, God of Harvests",
 "Arcanist's Owl",
 "Bident of Thassa",
 "Attunement",
 "Resplendent Angel",
 "Hammer of Purphoros",
 "Gravebreaker Lamia",
 "Master of Waves",
 "Karametra's Acolyte",
 "Overbeing of Myth",
 "Cleric Class",
 "Khalni Hydra",
 "Greater Good",
 "Fire Covenant",
 "Well of Lost Dreams",
 "Veinwitch Coven",
 "Fanatic of Rhonas",
 "Ramos, Dragon Engine",
 "Blade Historian",
 "Selvala, Heart of the Wilds",
 "Leyline of the Guildpact",
 "Penance",
 "Cryptolith Rite",
 "Enduring Innocence"
];
export function installGods(registry){
 installGodsShared(registry);installGodsMana(registry);installGodsEnchantments(registry);installGodsLife(registry);installGodsSpells(registry);
}
