import { sequenceBody,automationBody } from './program-views.js';
import { dialogHTML as originalDialog } from '../ui/dialogs.js';
import { h, asset, button, manaText } from '../ui/components.js';
import { menuBody } from './views.js';
import { deckCounts, supportedCards, poolLabel } from './deck-editor.js';

function membershipBadges(membership={}) {
  return ['main','command','outside'].filter(pool=>membership[pool]).map(pool=>`<span title="${h(poolLabel(pool))}">${pool==='main'?'M':pool==='command'?'C':'O'}${membership[pool]}</span>`).join('');
}
function deckEditor(ctx) {
  const {ui,registry}=ctx, counts=deckCounts(ui.deckText,registry), tab=ui.deckTab||'main';
  const filters={query:ui.deckSearch||'',type:ui.deckType||'',color:ui.deckColor||'',sort:ui.deckSort||'name'}, cards=supportedCards(registry,filters);
  const tabRecords=counts.records.filter(row=>row.pool===tab);
  const typeOptions=['Artifact','Creature','Enchantment','Instant','Sorcery','Land','Planeswalker'];
  const status=ui.deckReport ? `<div class="deck-live-status ${ui.deckReport.accepted?'ready':'needs-work'}"><strong>${ui.deckReport.accepted?'Ready for New test':'Needs attention'}</strong><span>${h(ui.deckReport.summary)}</span></div>` : '';
  const browser=cards.map(card=>{
    const member=counts.membership[card.name.toLowerCase()]||{}, badges=membershipBadges(member);
    return `<article class="deck-browser-card" draggable="true" data-deck-drag="database" data-card-name="${h(card.name)}" title="Drag ${h(card.name)} into a deck section">
      <div class="deck-browser-art">${badges?`<div class="deck-membership">${badges}</div>`:''}<button type="button" class="deck-card-preview" data-action="zoom" data-card-id="${h(card.id)}" title="Inspect ${h(card.name)}"><img src="${h(asset(card.image))}" alt="${h(card.name)}" loading="lazy"></button></div>
      <div class="deck-browser-caption"><strong>${h(card.name)}</strong><span>${manaText(card.manaCost)} <small>${h(card.typeLine)}</small></span></div>
      <button type="button" class="deck-quick-add" data-action="deck-add" data-card-name="${h(card.name)}" data-pool="${h(tab)}" title="Add one to ${h(poolLabel(tab))}" aria-label="Add ${h(card.name)} to ${h(poolLabel(tab))}">+</button>
    </article>`;
  }).join('');
  const entries=tabRecords.map(row=>{
    const supported=registry.has(row.name), card=supported?registry.get(row.name):null;
    return `<article class="deck-entry ${supported?'':'unsupported'}" draggable="true" data-deck-drag="deck" data-deck-drop-before="${h(row.name)}" data-card-name="${h(row.name)}" data-pool="${h(row.pool)}" data-quantity="${row.quantity}" title="Drag to move this entry to another section">
      ${card?`<img src="${h(asset(card.image))}" alt="" loading="lazy">`:'<div class="deck-entry-missing">?</div>'}
      <div class="deck-entry-name"><strong>${h(row.name)}</strong><small>${card?h(card.typeLine):'Unsupported card name'}</small></div>
      <div class="deck-quantity" aria-label="Quantity for ${h(row.name)}">${button('−','deck-adjust',`data-card-name="${h(row.name)}" data-pool="${h(row.pool)}" data-delta="-1" aria-label="Remove one ${h(row.name)}"`)}<input type="number" min="0" max="1000" value="${row.quantity}" data-deck-qty data-card-name="${h(row.name)}" data-pool="${h(row.pool)}" aria-label="${h(row.name)} quantity">${button('+','deck-adjust',`data-card-name="${h(row.name)}" data-pool="${h(row.pool)}" data-delta="1" aria-label="Add one ${h(row.name)}"`)}</div>
      ${button('×','deck-remove',`data-card-name="${h(row.name)}" data-pool="${h(row.pool)}" title="Remove all copies of ${h(row.name)}" aria-label="Remove all copies of ${h(row.name)}"`,'quiet deck-remove')}
    </article>`;
  }).join('');
  return `<details class="deck-preset-picker"><summary>Load one of your supplied lists</summary><p>Replaces the editor only, not your current game.</p><div class="row">${(globalThis.ASTRA_DATA?.deckPresets||[]).map(p=>button(h(p.label),'deck-preset',`data-preset="${h(p.id)}"`)).join('')}</div></details><div class="deck-editor-summary">
    <div><strong>${counts.main}</strong><small>Main pool</small></div><div><strong>${counts.lands}</strong><small>Fixed lands</small></div><div><strong>${counts.reserve}</strong><small>Seeded reserve</small></div><div><strong>${counts.command}</strong><small>Commander</small></div><div><strong>${counts.outside}</strong><small>Outside</small></div>
  </div>${status}
  <div class="deck-editor-shell">
    <section class="deck-browser-panel">
      <div class="deck-search-tools"><input id="deck-search" value="${h(filters.query)}" placeholder="Search ${registry.list().filter(c=>c.candidate).length} supported cards…" autocomplete="off" aria-label="Search supported cards"><select id="deck-type" aria-label="Filter card type"><option value="">All types</option>${typeOptions.map(v=>`<option ${filters.type===v?'selected':''}>${v}</option>`).join('')}</select><select id="deck-color" aria-label="Filter color identity"><option value="">All colors</option><option value="C" ${filters.color==='C'?'selected':''}>Colorless</option>${['W','U','B','R','G'].map(v=>`<option value="${v}" ${filters.color===v?'selected':''}>${v}</option>`).join('')}<option value="M" ${filters.color==='M'?'selected':''}>Multicolor</option></select><select id="deck-sort" aria-label="Sort cards"><option value="name" ${filters.sort==='name'?'selected':''}>Name</option><option value="mv" ${filters.sort==='mv'?'selected':''}>Mana value</option><option value="type" ${filters.sort==='type'?'selected':''}>Type</option></select></div>
      <div class="deck-browser-heading"><span><b>${cards.length}</b> supported cards</span><small>Drag a card right, or press + to add to ${h(poolLabel(tab))}.</small></div>
      <div class="deck-browser-grid" data-modal-scroll="deck-browser">${browser||'<div class="deck-empty">No supported cards match those filters.</div>'}</div>
    </section>
    <section class="deck-build-panel">
      <div class="deck-drop-tabs">${['main','command','outside'].map(pool=>`<button type="button" class="deck-pool-target ${tab===pool?'active':''}" data-action="deck-tab" data-pool="${pool}" data-deck-drop="${pool}" title="Drop cards here to move/add them to ${h(poolLabel(pool))}"><span>${h(poolLabel(pool))}</span><b>${counts[pool]}</b></button>`).join('')}<div class="deck-trash-target" data-deck-drop="remove" title="Drop a deck entry here to remove all copies">⌫ <span>Remove</span></div></div>
      <div class="deck-section-heading"><div><strong>${h(poolLabel(tab))}</strong><small>${tabRecords.length} names · ${counts[tab]} copies</small></div><span class="muted">Drag entries onto another section above, or onto Remove.</span></div>
      <div class="deck-entry-list" data-deck-drop="${h(tab)}" data-modal-scroll="deck-list">${entries||`<div class="deck-empty">Drop supported cards here to add them to ${h(poolLabel(tab))}.</div>`}</div>
    </section>
  </div>
`;
}
function deckTextEditor(ctx){
  const {ui,registry}=ctx,counts=deckCounts(ui.deckText,registry),report=ui.deckReport;
  const status=report?`<div class="deck-live-status ${report.accepted?'ready':'needs-work'}"><strong>${report.accepted?'Ready for New test':'Needs attention'}</strong><span>${h(report.summary)}</span></div>`:'';
  return `<div class="deck-text-toolbar"><div><strong>${counts.main}</strong> main · <strong>${counts.command}</strong> commander · <strong>${counts.outside}</strong> outside · <strong>${counts.reserve}</strong> reserve</div><small>Old-style quantity/name editor. Visual and text editors use the same deck.</small></div>${status}${report&&!report.accepted?`<pre class="deck-text-issues" role="status">${h(report.details)}</pre>`:''}<textarea id="deck-text" data-modal-scroll="deck-text" class="deck-text-area" spellcheck="false" aria-label="Deck list">${h(ui.deckText)}</textarea><div class="deck-text-help"><code>// Main</code><code>// Commander</code><code>// Outside the Game</code><span>One entry per line, e.g. <b>2 Arcbound Ravager</b>.</span></div>`;
}

export function dialogs(ctx){
  const {g,ui,prefs,registry}=ctx,s=g.state;let title='',sub='',body='',footer='',narrow=false;
  if(!ui.modal)return '';
  if(ui.modal==='menu'){title='Astra';sub='The Goldfish Lab · 1.4.7';narrow=true;body=menuBody(ctx);}
  else if(ui.modal==='sequences'){title='Sequences & loops';sub='Record once. Check every iteration. Undo a whole iteration at once.';body=sequenceBody(ctx);}
  else if(ui.modal==='automation'){title='Player automations';sub='Your conditional actions and priority stops. Easy to toggle, nothing forced.';body=automationBody(ctx);}
  else if(ui.modal==='deck'){title='Deck editor';sub='Search the supported database, then drag cards between sections. Changes apply to your next New test.';body=deckEditor(ctx);footer=button('Text editor','dialog','data-dialog="decktext"')+button('Restore supplied pool','restore-pool')+button('Export missing-card report','export-report')+button('Validate deck','validate-deck')+button('Done','close-dialog','','primary');}
  else if(ui.modal==='decktext'){title='Deck text editor';sub='The original quantity/name editor, kept separate from the visual builder.';body=deckTextEditor(ctx);footer=button('Visual editor','dialog','data-dialog="deck"')+button('Load List 1','deck-preset','data-preset="expanded"')+button('Load List 2','deck-preset','data-preset="refined"')+button('Restore supplied pool','restore-pool')+button('Export missing-card report','export-report')+button('Validate','deck-apply-text')+button('Done','close-dialog','','primary');}
  else if(ui.modal==='settings'){
    title='Settings';sub='Your table layout is saved automatically.';
    const setting=(key,name,help)=>`<div class="setting-row"><input id="setting-${key}" type="checkbox" data-setting="${key}" ${s.settings[key]?'checked':''}><label for="setting-${key}"><strong>${name}</strong><small>${help}</small></label></div>`;
    body=`${setting('holdPriority','Hold priority','Off: automatically resolve after casting or activating, pausing for choices. On: keep the stack to respond.')}${setting('orderTriggers','Choose simultaneous trigger order','Choose which of your simultaneous triggers resolves first.')}${setting('firstMulliganFree','First mulligan is free','Later mulligans use London bottoming.')}<div class="setting-row"><input id="reserve-access" type="checkbox" ${s.reserveAccess?'checked':''}><label for="reserve-access"><strong>Allow reserve access</strong><small>On by default. Searches can include reserve candidates; the reserve stays beneath the active library.</small></label></div><div class="setting-row"><span class="grow"><strong>Saved table layout</strong><small>Drag the rail, hand and side-zone dividers. Wheel over a table to zoom. Drag popup title bars to move them.</small></span>${button('Reset layout','reset-layout')}</div><h3 style="margin-top:14px">Abstract opponents</h3>${s.players.slice(1).map(p=>`<div class="setting-row"><strong>OP${p.id}</strong><label>Creatures <input type="number" min="0" max="1000" data-player-field="abstractCreatures" data-player="${p.id}" value="${p.abstractCreatures}"></label><label>Hand <input type="number" min="0" max="1000" data-player-field="abstractHand" data-player="${p.id}" value="${p.abstractHand}"></label></div>`).join('')}${Object.keys(s.optionalPreferences).length?'<h3 style="margin-top:14px">Remembered choices</h3>':''}${Object.entries(s.optionalPreferences).map(([key,value])=>{const [id,name]=key.split('/'),options=key.endsWith('/token-kind')?['ASK','Treasure','Food']:['ASK','YES','NO'];return `<div class="setting-row"><label class="grow">${h(registry.has(id)?registry.get(id).name:id)}<small>${h(name)}</small></label><select data-policy="${h(key)}">${options.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`;}).join('')}${setting('debug','Developer overrides','Off by default. Overrides are marked in the action log and are not rules-valid play.')}${s.settings.debug?`<div class="row wrap" style="margin-top:10px"><select id="debug-card">${registry.list().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${h(c.id)}">${h(c.name)}</option>`).join('')}</select><select id="debug-zone"><option value="battlefield">Battlefield</option><option value="hand">Hand</option><option value="graveyard">Graveyard</option></select>${button('Spawn','debug-spawn','','danger')}<input id="debug-count" type="number" value="1" min="0" max="1000">${button('Draw','debug-draw','','danger')}${button('Mill','debug-mill','','danger')}${button('Shuffle','debug-shuffle','','danger')}</div>`:''}`;
  }else if(ui.modal==='log'){
    title='Action log';sub=`${g.cursor} committed actions`;
    body=`${[...(g.transaction?[{index:'…',label:g.transaction.label,events:g.transaction.events}]:[]),...g.history.slice(0,g.cursor).reverse()].map(e=>`<details class="log-entry"><summary>${e.index} · ${h(e.label)} <small>${e.events.length} events</small></summary><pre>${h(JSON.stringify(e.events,null,2))}</pre></details>`).join('')||'<p>No actions yet.</p>'}`;
    footer=button('Export readable log','export-text');
  }else if(ui.modal==='notes'){
    title='Testing notes';narrow=true;body=`<textarea id="note-text" rows="4" placeholder="Record a line or an awkward card…">${h(ui.noteText)}</textarea>${button('Add note','note','','primary')}${[...s.notes].reverse().map(n=>`<div class="note"><small>Turn ${n.turn}</small>${h(n.text)}</div>`).join('')}`;
  }else if(ui.modal==='mana'){
    title='Restricted mana';narrow=true;body=s.players[0].restrictedMana.map(t=>`<p><strong>${t.amount} ${h(t.color)}</strong> · ${h(t.restriction)}</p>`).join('')||'<p>No restricted mana.</p>';
  }else if(ui.modal==='guide'){
    title='Play on the table';sub='A compact offline goldfish workspace.';
    body=`<div class="guide-grid"><section><h3>Cards and mana</h3><p>Click a card to inspect it; click the same card again to close. Untapped lands and permanents with one tap-mana ability use that ability on click. Mana sources with extra actions show a small ⋯ Abilities button: click it to inspect without tapping. The artwork still provides quick mana. The button also works by keyboard or touch; right-click remains available. Already-tapped sources cannot ask for mana colors. Drag a hand card onto the battlefield to request a legal play or cast. The exact drop position is kept through payment and resolution.</p><p>Tap mana sources directly on the battlefield while paying. Sources with multiple colors ask which color to add. The payment window stays separate from the table. Pay uses the suggested allocation unless you edit it; it never taps anything automatically.</p><h3>Move and stack</h3><p>The grabbed point stays under your pointer. Hover uses the original stack order, so crossing onto an upper card immediately selects that upper card. On a drop, cursor-covered cards go below the dragged card; overlapping cards not under the cursor go above it. This lets you insert cards into a stack.</p><p>Tapped cards rotate clockwise, bringing the card’s original bottom-right corner to its untapped bottom-left anchor. Select mode, Shift-click and dragging a selection rectangle support groups.</p></section><section><h3>Make room</h3><p>Wheel over the battlefield or side zone to zoom around the pointer. Drag empty space to pan, or hold Space and drag. The small fit icon shows every card again. The battlefield is always visible. Graveyard, exile and outside-the-game open alongside it.</p><p>Drag the left rail divider to change width, the hand divider to change height, and the side-zone divider to change width. Cards in hand grow or shrink with the row. Move inspector, stack and decision windows by their title bars. Layout and zoom are remembered.</p><h3>Look, stack and shortcuts</h3><p>The eye icon appears only for a temporary multi-card workspace created by effects such as looking at, revealing or reordering several cards. It is not the top-card display: a legal top-card view replaces the library back automatically.</p><p>Gold borders mark spells on the stack; teal borders mark abilities and triggers. Hover a stack image for its exact effect. Hold priority is off by default; switch it on in Menu to respond before resolution.</p><p><kbd>Esc</kbd> cancels or declines the active decision, closes a dialog, or dismisses inspection. <kbd>Backspace</kbd> or <kbd>Ctrl Z</kbd> undoes outside text fields. <kbd>Ctrl Shift Z</kbd> redoes. <kbd>Ctrl S</kbd> exports a portable game.</p></section></div><div class="callout">Save / import preserves the game and table layout between computers. Browser autosave is local to its browser profile and file/origin. Opponents are abstract; blocking and combat-damage assignment remain explicitly user-assisted.</div>`;
  }else return originalDialog(ctx);
  if(ui.modal==='settings')body+=`<label class="setting-row"><input type="checkbox" data-auto-accept ${prefs.autoAccept?'checked':''}> Auto-accept completed selections <small>Single targets accept on click; multi-select accepts at its required maximum or sufficient crew power.</small></label>`;
  if(ui.modal==='settings'){
    body=`<label class="setting-row"><input type="checkbox" data-setting="manualControls" ${s.settings.manualControls?'checked':''}><span><strong>Manual controls</strong><small>Off by default. Show manual mana, life, energy, poison and opponent adjustments. Rules-generated changes remain automatic.</small></span></label>`+body;
    if(!s.settings.manualControls)body=body.replace(/<input([^>]*data-player-field[^>]*)>/g,'<input disabled$1>');
  }
  const extraClass=ui.modal==='deck'?'deck-editor-modal':ui.modal==='decktext'?'deck-text-modal':'';
  return `<div class="modal-backdrop" data-action="backdrop"><section class="modal ${narrow?'narrow':''} ${extraClass}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header"><div><h2 id="modal-title">${h(title)}</h2><p>${h(sub)}</p></div>${button('×','close-dialog','aria-label="Close dialog"','quiet')}</header><div class="modal-body" data-scroll="modal">${body}</div>${footer?`<footer class="modal-footer">${footer}</footer>`:''}</section></div>`;
}
