import { dialogHTML as originalDialog } from '../ui/dialogs.js';
import { h, button, saveDownload } from '../ui/components.js';
import { menuBody } from './views.js';
export function dialogs(ctx){
  const {g,ui,prefs,registry}=ctx,s=g.state;let title='',sub='',body='',footer='',narrow=false;
  if(!ui.modal)return '';
  if(ui.modal==='menu'){title='Astra';sub='The Goldfish Lab · 1.1';narrow=true;body=menuBody(ctx);}
  else if(ui.modal==='settings'){
    title='Settings';sub='Your table layout is saved automatically.';
    const setting=(key,name,help)=>`<div class="setting-row"><input id="setting-${key}" type="checkbox" data-setting="${key}" ${s.settings[key]?'checked':''}><label for="setting-${key}"><strong>${name}</strong><small>${help}</small></label></div>`;
    body=`${setting('holdPriority','Hold priority','Off: automatically resolve after casting or activating, pausing for choices. On: keep the stack to respond.')}${setting('orderTriggers','Choose simultaneous trigger order','Choose which of your simultaneous triggers resolves first.')}${setting('firstMulliganFree','First mulligan is free','Later mulligans use London bottoming.')}<div class="setting-row"><input id="reserve-access" type="checkbox" ${s.reserveAccess?'checked':''}><label for="reserve-access"><strong>Allow reserve access</strong><small>On by default. Searches can include reserve candidates; the reserve stays beneath the active library.</small></label></div><div class="setting-row"><span class="grow"><strong>Saved table layout</strong><small>Drag the rail, hand and side-zone dividers. Wheel over a table to zoom. Drag popup title bars to move them.</small></span>${button('Reset layout','reset-layout')}</div><h3 style="margin-top:14px">Abstract opponents</h3>${s.players.slice(1).map(p=>`<div class="setting-row"><strong>OP${p.id}</strong><label>Creatures <input type="number" min="0" max="1000" data-player-field="abstractCreatures" data-player="${p.id}" value="${p.abstractCreatures}"></label><label>Hand <input type="number" min="0" max="1000" data-player-field="abstractHand" data-player="${p.id}" value="${p.abstractHand}"></label></div>`).join('')}${Object.keys(s.optionalPreferences).length?'<h3 style="margin-top:14px">Remembered choices</h3>':''}${Object.entries(s.optionalPreferences).map(([key,value])=>{const [id,name]=key.split('/'),options=key.endsWith('/token-kind')?['ASK','Treasure','Food']:['ASK','YES','NO'];return `<div class="setting-row"><label class="grow">${h(registry.has(id)?registry.get(id).name:id)}<small>${h(name)}</small></label><select data-policy="${h(key)}">${options.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`;}).join('')}${setting('debug','Developer overrides','Off by default. Overrides are marked in the action log and are not rules-valid play.')}${s.settings.debug?`<div class="row wrap" style="margin-top:10px"><select id="debug-card">${registry.list().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${h(c.id)}">${h(c.name)}</option>`).join('')}</select><select id="debug-zone"><option value="battlefield">Battlefield</option><option value="hand">Hand</option><option value="graveyard">Graveyard</option></select>${button('Spawn','debug-spawn','','danger')}<input id="debug-count" type="number" value="1" min="0" max="1000">${button('Draw','debug-draw','','danger')}${button('Mill','debug-mill','','danger')}${button('Shuffle','debug-shuffle','','danger')}</div>`:''}`;
  }else if(ui.modal==='log'){
    title='Action log';sub=`${g.cursor} committed actions`;
    body=`${[...(g.transaction?[{index:'…',label:g.transaction.label,events:g.transaction.events}]:[]),...g.history.slice(0,g.cursor).reverse()].map(e=>`<details class="log-entry"><summary>${e.index} · ${h(e.label)} <small>${e.events.length} events</small></summary><pre>${h(JSON.stringify(e.events,null,2))}</pre></details>`).join('')||'<p>No actions yet.</p>'}`;
    footer=button('Export readable log','export-text');
  }else if(ui.modal==='notes'){
    title='Testing notes';narrow=true;body=`<textarea id="note-text" rows="4" placeholder="Record a line or an awkward card…">${h(ui.noteText)}</textarea>${button('Add note','note','','primary')}${[...s.notes].reverse().map(n=>`<div class="note"><small>Turn ${n.turn}</small>${h(n.text)}</div>`).join('')}`;
  }else if(ui.modal==='mana'){
    title='Restricted mana';narrow=true;body=s.players[0].restrictedMana.map(t=>`<p><strong>${t.amount} ${h(t.color)}</strong> · ${h(t.restriction)}</p>`).join('')||'<p>No restricted mana.</p>';
  }else if(ui.modal==='guide'){
    title='Play on the table';sub='A compact offline goldfish workspace.';
    body=`<div class="guide-grid"><section><h3>Cards and mana</h3><p>Click a card to inspect it; click the same card again to close. Untapped lands and permanents with one tap-mana ability use that ability on click. Right-click always opens the inspector. Already-tapped sources cannot ask for mana colors. Drag a hand card onto the battlefield to request a legal play or cast. The exact drop position is kept through payment and resolution.</p><p>Tap mana sources directly on the battlefield while paying. Sources with multiple colors ask which color to add. The payment window stays separate from the table. Pay uses the suggested allocation unless you edit it; it never taps anything automatically.</p><h3>Move and stack</h3><p>The grabbed point stays under your pointer. Hover uses the original stack order, so crossing onto an upper card immediately selects that upper card. On a drop, cursor-covered cards go below the dragged card; overlapping cards not under the cursor go above it. This lets you insert cards into a stack.</p><p>Tapped cards physically rotate counter-clockwise around their upright bottom-left corner. That point becomes their sideways bottom-right corner. Select mode, Shift-click and dragging a selection rectangle support groups.</p></section><section><h3>Make room</h3><p>Wheel over the battlefield or side zone to zoom around the pointer. Drag empty space to pan, or hold Space and drag. The small fit icon shows every card again. The battlefield is always visible. Graveyard, exile and outside-the-game open alongside it.</p><p>Drag the left rail divider to change width, the hand divider to change height, and the side-zone divider to change width. Cards in hand grow or shrink with the row. Move inspector, stack and decision windows by their title bars. Layout and zoom are remembered.</p><h3>Look, stack and shortcuts</h3><p>The eye icon appears only for a temporary multi-card workspace created by effects such as looking at, revealing or reordering several cards. It is not the top-card display: a legal top-card view replaces the library back automatically.</p><p>Gold borders mark spells on the stack; teal borders mark abilities and triggers. Hover a stack image for its exact effect. Hold priority is off by default; switch it on in Menu to respond before resolution.</p><p><kbd>Esc</kbd> cancels or declines the active decision, closes a dialog, or dismisses inspection. <kbd>Backspace</kbd> or <kbd>Ctrl Z</kbd> undoes outside text fields. <kbd>Ctrl Shift Z</kbd> redoes. <kbd>Ctrl S</kbd> exports a portable game.</p></section></div><div class="callout">Save / import preserves the game and table layout between computers. Browser autosave is local to its browser profile and file/origin. Opponents are abstract; blocking and combat-damage assignment remain explicitly user-assisted.</div>`;
  }else return originalDialog(ctx);
  return `<div class="modal-backdrop" data-action="backdrop"><section class="modal ${narrow?'narrow':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header"><div><h2 id="modal-title">${h(title)}</h2><p>${h(sub)}</p></div>${button('×','close-dialog','aria-label="Close dialog"','quiet')}</header><div class="modal-body" data-scroll="modal">${body}</div>${footer?`<footer class="modal-footer">${footer}</footer>`:''}</section></div>`;
}
