import { h, button } from '../ui/components.js';
import { EVENTS } from './programs.js';
const field=(label,html)=>`<label class="program-field"><span>${label}</span>${html}</label>`;
const select=(id,options,value)=>`<select id="${id}">${options.map(([v,label])=>`<option value="${h(v)}" ${String(v)===String(value)?'selected':''}>${h(label)}</option>`).join('')}</select>`;
export function sequenceBody({ui,programs}) {
  const recording=programs.recording,job=programs.running,model=programs.model;
  return `<div class="program-intro"><p>Record a legal line of play, including its costs and choices. Each run checks the entire line before changing the game. It never invents missing targets or taps extra mana sources.</p>${recording?`<div class="program-recording"><strong>● Recording · ${recording.steps.length} steps</strong><p>Play your line on the table. Use Resolve for effects you want included. Automatic resolution and player rules are suspended during recording.</p>${field('Sequence name',`<input id="sequence-name" value="${h(ui.sequenceName||recording.name)}" maxlength="120">`)}<label><input id="sequence-future" type="checkbox" ${ui.sequenceFuture?'checked':''}> Save for future games</label><div class="row">${button('Save recording','sequence-save','','primary')}${button('Discard recording','sequence-discard')}</div></div>`:`<div class="row">${button('● Record a sequence','sequence-record','','primary')}${button('Automation rules','dialog','data-dialog="automation"')}</div>`}${job?`<div class="callout"><strong>Running ${job.completed} / ${job.count}</strong> ${button('Stop after this iteration','program-stop')}</div>`:''}${model.paused?`<div class="callout warning">${h(model.pauseReason)} ${button('Resume','program-resume')}</div>`:''}</div>
  <div class="program-list">${model.sequences.map(s=>`<article class="sequence-card" data-sequence-id="${h(s.id)}"><header><input aria-label="Sequence name" data-sequence-name="${h(s.id)}" value="${h(s.name)}" maxlength="120"><span>${s.steps.length} ${s.steps.length===1?'step':'steps'}</span>${button('×','sequence-delete',`data-sequence-id="${h(s.id)}" title="Delete sequence" aria-label="Delete ${h(s.name)}"`)}</header><div class="row wrap">${button('▶ Once','sequence-run',`data-sequence-id="${h(s.id)}" ${recording||job?'disabled':''}`,'primary')}<input type="number" min="1" max="1000" value="2" data-repeat="${h(s.id)}" aria-label="Repetitions for ${h(s.name)}">${button('↻ Repeat','sequence-repeat',`data-sequence-id="${h(s.id)}" ${recording||job?'disabled':''}`)}${button('Check legality','sequence-check',`data-sequence-id="${h(s.id)}"`)}<label><input type="checkbox" data-sequence-saved="${h(s.id)}" ${s.saved?'checked':''}> Save for future games</label></div><details><summary>Recorded steps</summary><p class="muted">Actions are checked against the current state. Ambiguous copies or changed choices stop safely. Removing a required choice can make a line incomplete.</p>${s.steps.map((step,i)=>`<div class="sequence-step"><span>${i+1}. ${h(step.label)}</span>${button('↑','sequence-step',`data-sequence-id="${h(s.id)}" data-index="${i}" data-direction="-1" ${!i?'disabled':''} title="Move step earlier"`)}${button('↓','sequence-step',`data-sequence-id="${h(s.id)}" data-index="${i}" data-direction="1" ${i===s.steps.length-1?'disabled':''} title="Move step later"`)}${button('×','sequence-step',`data-sequence-id="${h(s.id)}" data-index="${i}" data-direction="remove" title="Remove step"`)}</div>`).join('')}</details></article>`).join('')||'<div class="empty-programs">No sequences yet. Start recording, perform the actions on your table, then save the line.</div>'}</div>`;
}
export function automationBody({g,ui,registry,programs}) {
  const model=programs.model,r=ui.ruleDraft;
  const name=id=>registry.has(id)?registry.get(id).name:'Any card';
  const abilityLabel=r=>{const m=r.cardId?registry.module(r.cardId):{};return [...(m.activated||[]),...(m.triggers||[])].find(a=>a.id===r.abilityId)?.label||r.abilityId;};
  const cards=[['','Any card'],...registry.list().filter(c=>c.candidate).sort((a,b)=>a.name.localeCompare(b.name)).map(c=>[c.id,c.name])];
  let editor='';
  if(r) {
    const module=r.cardId?registry.module(r.cardId):{};
    const abilities=[['','Any spell / ability'],...(module.activated||[]).map(a=>[a.id,a.label||a.id]),...(module.triggers||[]).map(a=>[a.id,a.label||a.id])];
    const scopes=r.editing?[['game','Rest of this game'],['future','This and future games'],...(r.scope==='stack'?[['stack',`Selected stack objects (${r.stackIds.length})`]]:[])]:r.stackContext?[['one','This stack object only'],['current','All matching objects currently on stack'],['game','All matching objects for this game'],['future','This and future games']]:[['future','This and future games'],['game','This game only']];
    editor=`<form id="rule-form" class="rule-editor"><div class="spread"><h3>${r.editing?'Edit rule':'New rule'}</h3>${button('×','rule-cancel','aria-label="Close rule editor"')}</div><div class="program-form-grid">${field('Name',`<input id="rule-name" value="${h(r.name)}" maxlength="120" required>`)}${field('When',select('rule-event',EVENTS,r.event))}${field('Card',select('rule-card',cards,r.cardId))}${field('Ability / effect',select('rule-ability',abilities,r.abilityId))}${field('Do',select('rule-action',[['hold','Hold priority (only with a nonempty stack)'],['sequence','Run a sequence'],['sequenceHold','Run a sequence, then hold priority']],r.action))}${field('Sequence',select('rule-sequence',[['','Choose a sequence'],...model.sequences.map(s=>[s.id,s.name])],r.sequenceId))}${field('Applies to',select('rule-scope',scopes,r.scope))}${field('Conditions',select('rule-match',[['all','All conditions must match'],['any','Any condition may match']],r.conditionMatch))}</div><div class="rule-conditions">${r.conditions.map((c,i)=>`<div class="row">${select('condition-card-'+i,cards.slice(1),c.cardId)}${select('condition-test-'+i,[['present','You control it'],['absent','You do not control it'],['untapped','You control an untapped copy']],c.test)}${button('×','rule-condition-remove',`data-index="${i}" title="Remove condition"`)}</div>`).join('')}${button('+ Condition','rule-condition-add')}</div><label><input id="rule-enabled" type="checkbox" ${r.enabled?'checked':''}> Enabled</label><p class="muted">Rules execute only when the current effect and all mandatory choices are complete. Before-resolution rules run at priority before the selected object resolves. A failed sequence leaves the iteration unchanged and pauses automation.</p><div class="row">${button('Save rule','rule-save','','primary')}${button('Cancel','rule-cancel')}</div></form>`;
  }
  return `<div class="program-intro"><p>These are your shortcuts, not card rules. Nothing is enabled until you create it. Turn a rule off without deleting it; future-game rules and their sequences travel with session exports.</p><div class="row">${button('+ New rule','rule-new','','primary')}${button('Sequences','dialog','data-dialog="sequences"')}${model.paused?button('▶ Resume','program-resume'):button('Ⅱ Pause automation','program-stop')}</div>${model.paused?`<div class="callout warning">${h(model.pauseReason)}</div>`:''}</div>${editor}<div class="program-list">${model.rules.map(rule=>`<article class="rule-card" data-rule-id="${h(rule.id)}"><header><label><input type="checkbox" data-rule-toggle="${h(rule.id)}" ${rule.enabled?'checked':''}><strong>${h(rule.name)}</strong></label>${button('Edit','rule-edit',`data-rule-id="${h(rule.id)}"`)}${button('×','rule-delete',`data-rule-id="${h(rule.id)}" title="Delete rule"`)}</header><p>${h(EVENTS.find(([v])=>v===rule.event)?.[1])} · ${h(name(rule.cardId))}${rule.abilityId?' · '+h(abilityLabel(rule)):''}<br>${rule.action==='hold'?'Hold priority':h(model.sequences.find(s=>s.id===rule.sequenceId)?.name||'Missing sequence')+(rule.action==='sequenceHold'?' → hold priority':'')} · ${rule.scope==='future'?'Saved for future games':rule.scope==='stack'?rule.stackIds.length+' selected stack objects':'This game only'}</p>${rule.conditions.length?`<small>${rule.conditionMatch==='any'?'Any':'All'}: ${rule.conditions.map(c=>(c.test==='absent'?'do not control ':c.test==='untapped'?'control an untapped ':'control ')+h(name(c.cardId))).join(', ')}</small>`:''}</article>`).join('')||(!r?'<div class="empty-programs">No automatic actions or priority stops are configured.</div>':'')}</div>`;
}
