import { isManaColorChoice, manaChoiceHTML, manaGlyph } from './mana-choice.js';
import { COLORS, STEPS } from '../core/index.js';
import { h, asset, button, symbol, manaText, STEP_NAMES, ZONE_NAMES } from '../ui/components.js';
import { decisionHTML } from '../ui/views.js';
import { CARD_W, CARD_H } from './geometry.js';
const paths={loop:'M4 9a8 8 0 0 1 13-4l3 3M20 3v5h-5M20 15a8 8 0 0 1-13 4l-3-3M4 21v-5h5',auto:'m13 2-8 12h6l-1 8 9-13h-6Z',menu:'M4 6h16M4 12h16M4 18h16',graveyard:'M6 21V8a6 6 0 0 1 12 0v13M4 21h16M12 6v9M9 10h6',exile:'M5 5l14 14M19 5 5 19M4 12a8 8 0 1 0 8-8',workspace:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Zm7 0a3 3 0 1 0 6 0 3 3 0 0 0-6 0',outside:'M14 3h7v7M21 3 11 13M10 5H4v15h15v-6',select:'M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4M8 8h8v8H8Z',arrange:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',fit:'M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6M8 8h8v8H8Z',hand:'M8 7 4 8l-2 11 5 1M9 6l5-1 4 13-7 2ZM15 5l4-1 4 12-4 2',land:'M2 20 9 6l4 7 3-5 6 12ZM7 10l2 3 2-3',close:'M5 5l14 14M19 5 5 19',stack:'m3 7 9-4 9 4-9 4ZM3 12l9 4 9-4M3 17l9 4 9-4',inspect:'M15 15l6 6M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',undo:'M4 4v7h7M4 11a8 8 0 1 1 1 7',redo:'M20 4v7h-7M20 11a8 8 0 1 0-1 7',hold:'M8 4v16M16 4v16',play:'m7 4 13 8-13 8Z'};
export const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.menu}"/></svg>`;
const tool=(name,action,attributes='',active=false)=>button(icon(name),action,`title="${h({graveyard:'Graveyard',exile:'Exile',workspace:'Look at cards from a resolving effect',outside:'Outside the game',select:'Select cards / drag a selection box',arrange:'Arrange active area',fit:'Fit all cards in view',menu:'Menu',close:'Close'}[name]||name)}" aria-label="${h({workspace:'Look workspace',select:'Select cards',arrange:'Arrange cards',fit:'Fit view'}[name]||name)}" ${attributes}`,`icon-button ${active?'active':''}`);
export function programControls({programs}){return `${button(icon('loop'),'dialog','data-dialog="sequences" title="Sequences and loops" aria-label="Sequences and loops"','icon-button')}${button(icon('auto'),'dialog','data-dialog="automation" title="Player automations" aria-label="Player automations"','icon-button')}${programs?.recording?button('● '+programs.recording.steps.length,'dialog','data-dialog="sequences" title="Stop and save recording"','record-indicator'):''}${programs?.running?button('■ '+programs.running.completed+'/'+programs.running.count,'program-stop','title="Stop sequence"'):''}${programs?.model.paused?button('▶','program-resume',`title="${h(programs.model.pauseReason)} Resume" aria-label="Resume automation"`,'active'):''}`;}
export function toolbar({g,ui,prefs,programs}){
  const s=g.state;
  return `<header class="toolbar"><div class="toolbar-section brand-mini">${tool('menu','menu',`aria-expanded="${ui.modal==='menu'}"`)}<span class="turn-chip" title="${s.activePlayer?'Opponent '+s.activePlayer:'Your turn'}">${s.activePlayer?'OP'+s.activePlayer:'You'} <b>${s.turnNumber}</b></span></div><nav class="toolbar-section phases" aria-label="Steps and phases">${STEPS.map(step=>button(h(STEP_NAMES[step]),'phase',`data-step="${step}" ${!s.started?'disabled':''}`,s.step===step?'active':'')).join('')}</nav><nav class="toolbar-section opponents-turns" aria-label="Opponent turns">${s.players.slice(1).map(p=>button(`OP${p.id}`,'opponent',`title="Opponent ${p.id} — advance to main 1" aria-label="Opponent ${p.id} turn" data-player="${p.id}" ${p.lost||!s.started?'disabled':''}`,s.activePlayer===p.id?'active':'')).join('')}</nav><div class="toolbar-section zone-tools">${['graveyard','exile',...(s.lookWorkspace?.ids?.length?['workspace']:[]),'outside'].map(z=>tool(z,'zone',`data-zone="${z}" data-count="${z==='workspace'?s.lookWorkspace.ids.length:s.zones[z].length}"`,prefs.dock===z)).join('')}${tool('select','select-mode',`aria-pressed="${ui.selectMode}"`,ui.selectMode)}${tool('arrange','arrange')}</div><div class="toolbar-section program-tools">${programControls({programs})}</div><div class="toolbar-section turn-tools">${button('Step →','next',`title="Next step" ${!s.started?'disabled':''}`)}${button('Next turn','next-player',`title="Next player's turn" ${!s.started?'disabled':''}`)}${button('Your next turn','next-turn',!s.started?'disabled':'')}${s.activePlayer===0&&s.step==='attackers'?button('Attack','dialog','data-dialog="combat"'):''}${['attackers','damage','endCombat'].includes(s.step)?button('Damage','dialog','data-dialog="damage"'):''}</div></header>`;
}
export function picture(g,id,extra={}){
  const o=g.object(id);if(!o)return '';const d=g.definition(o),c=g.characteristics(o);
  const marks=[...Object.entries(o.counters).filter(([,n])=>n).map(([k,n])=>`${n} ${k}`),...(o.token?['Token']:[]),...(o.flags.attacking?['Attack']:[]),...(o.damage?[`${o.damage} damage`]:[])];
  return `<article class="playing-card ${extra.selected?'selected':''} ${extra.legal?'legal':''} ${extra.classes||''}" data-card="${h(id)}" data-zone="${h(o.zone)}"><button type="button" class="face" data-action="card" data-id="${h(id)}" aria-label="${h(d.name)}${o.tapped?', tapped':''}" title="${h(d.name)}${o.tapped?' — tapped':''}"><img src="${h(asset(o.face&&d.backImage?d.backImage:d.image))}" alt="${h(d.name)}" draggable="false"><span class="missing-art">${h(d.name)}</span></button>${marks.length?`<span class="card-marks">${marks.map(m=>`<span>${h(m)}</span>`).join('')}</span>`:''}${c.types.includes('Creature')?`<span class="power-badge">${c.power}/${c.toughness}</span>`:''}</article>`;
}
export function sidebar({g,ui,prefs}){
  const s=g.state,p=s.players[0],top=g.canSeeTop()?g.top():null;
  const adjust=(player,field,label)=>{const value=s.players[player][field],name=player?`Opponent ${player} ${field==='life'?'Life':field}`:label;return `<div class="total-row"><span class="total-label" title="${h(player?'Opponent '+player:label)}">${h(label)}</span>${button('−','resource',`data-player="${player}" data-field="${field}" data-delta="-1" aria-label="Decrease ${h(name)}"`)}<b title="${h(name)}">${value}</b>${button('+','resource',`data-player="${player}" data-field="${field}" data-delta="1" aria-label="Increase ${h(name)}"`)}</div>`;};
  return `<aside class="rail" aria-label="Your cards and resources"><div class="library-deck" title="Your library">${top?picture(g,top.id):`<button class="deck-back" data-action="deck" aria-label="Your library" title="Your library"><img src="${h(asset('assets/card-back.jpg'))}" alt="Magic: The Gathering card back" draggable="false"></button>`}<span class="deck-count" title="Active library cards">${s.zones.libraryActive.length}</span><span class="reserve-count ${s.reserveAccess?'enabled':''}" title="${s.zones.libraryReserve.length} reserve cards · access ${s.reserveAccess?'enabled':'isolated'}">+${s.zones.libraryReserve.length}</span></div><div class="library-icons"><span title="Cards in hand" aria-label="${s.zones.hand.length} cards in hand">${icon('hand')}<b>${s.zones.hand.length}</b></span><span title="Land plays" aria-label="Land plays ${s.landPlaysUsed} of ${g.landAllowance()}">${icon('land')}<b>${s.landPlaysUsed}/${g.landAllowance()}</b></span></div><div class="command-slot" title="Command zone"><span class="watermark">COMMAND ZONE</span>${s.zones.command.map(id=>picture(g,id)).join('')}</div><div class="mana-title">Mana pool ${button('×','clear-mana','title="Clear mana pool" aria-label="Clear mana pool"')}</div><div class="mana-rows">${COLORS.map(c=>`<div class="mana-row"><span title="${{W:'White',U:'Blue',B:'Black',R:'Red',G:'Green',C:'Colorless'}[c]}">${manaGlyph(c)}</span>${button('−','mana',`data-color="${c}" data-delta="-1" aria-label="Remove ${c} mana" ${p.mana[c]===0?'disabled':''}`)}<b>${p.mana[c]}</b>${button('+','mana',`data-color="${c}" data-delta="1" aria-label="Add ${c} mana"`)}</div>`).join('')}</div>${p.restrictedMana.length?`<button class="restricted-summary" data-action="dialog" data-dialog="mana" title="Restricted mana: ${h(p.restrictedMana.map(t=>`${t.amount} ${t.color} ${t.restriction}`).join(', '))}">+${p.restrictedMana.reduce((a,t)=>a+t.amount,0)} restricted</button>`:''}<div class="totals">${adjust(0,'life','Life')}${adjust(0,'energy','Energy')}${adjust(0,'poison','Poison')}</div><div class="opponents-totals">${s.players.slice(1).map(p=>adjust(p.id,'life','OP'+p.id)).join('')}</div></aside><div class="resize-line rail-resize" data-resize="sidebar" role="separator" aria-label="Resize left column" aria-orientation="vertical" tabindex="0"></div>`;
}
export function surfaceHTML(ctx,zone,cards){
  const {g,ui,prefs}=ctx,camera=prefs.cameras[zone]||{x:0,y:0,zoom:1},p=g.state.pending,legal=p?.candidates||p?.ids||[];
  return `<div class="surface ${ui.selectMode?'selecting':''}" data-surface="${zone}" aria-label="${h(ZONE_NAMES[zone])}" tabindex="-1"><div class="world" style="transform:translate(${camera.x}px,${camera.y}px) scale(${camera.zoom})">${cards.map(c=>`<div class="card-position ${c.tapped?'tapped':''}" data-position="${h(c.id)}" data-layer="${c.z}" style="left:${c.x}px;top:${c.y-CARD_H}px;z-index:${c.z}">${picture(g,c.id,{selected:ui.selected.has(c.id),legal:legal.includes(c.id)})}</div>`).join('')}</div>${!cards.length?`<div class="empty-table">${zone==='battlefield'?'':h(ZONE_NAMES[zone])+' is empty'}</div>`:''}<div class="view-control" title="Wheel to zoom · drag empty space to pan"><span data-zoom-label="${zone}">${Math.round(camera.zoom*100)}%</span>${tool('fit','fit',`data-zone="${zone}"`)}</div></div>`;
}
export function tabletop(ctx){
  const {g,ui,prefs}=ctx,s=g.state,dock=prefs.dock;
  return `<div class="table-shell">${sidebar(ctx)}<main class="table-main"><div class="play-row">${surfaceHTML(ctx,'battlefield',ui.layouts.battlefield||[])}${dock?`<div class="resize-line dock-resize" data-resize="dock" role="separator" aria-label="Resize side zone" aria-orientation="vertical" tabindex="0"></div><section class="zone-dock"><div class="dock-header"><b>${h(ZONE_NAMES[dock])} <small>${ui.layouts[dock]?.length||0}</small></b>${tool('arrange','arrange',`data-zone="${dock}" title="Return all cards to grid"`)}${tool('close','close-zone')}</div>${surfaceHTML(ctx,dock,ui.layouts[dock]||[])}</section>`:''}</div><div class="resize-line hand-resize" data-resize="hand" role="separator" aria-label="Resize hand" aria-orientation="horizontal" tabindex="0"></div><div class="hand" aria-label="Your hand">${s.zones.hand.map((id,index)=>`<div class="hand-position" data-hand-position="${h(id)}" data-layer="${index}" style="z-index:${index}">${picture(g,id,{selected:ui.selected.has(id),legal:(s.pending?.candidates||[]).includes(id)})}</div>`).join('')}</div></main></div>`;
}
export function floating(name,title,body,tools='',classes=''){
  return `<section class="floating ${classes}" data-floating="${name}" role="dialog" aria-modal="false" aria-label="${h(title)}"><header class="float-header" data-drag-panel="${name}"><strong>${h(title)}</strong><span class="grow"></span>${tools}</header><div class="float-body" data-scroll="${name}">${body}</div></section>`;
}
export function stackPopup({g,ui,registry}){
  const s=g.state,entries=[...s.stack].reverse();if(s.resolving)entries.unshift({...s.resolving.object,resolving:true});
  if(!entries.length)return '';
  const body=`<div class="stack-gallery">${entries.map((v,i)=>{const o=g.object(v.source),d=o?g.definition(o):(v.context?.sourceSnapshot?.definition||registry.get(v.sourceCardId));return `<div class="stack-entry"><button class="stack-card ${v.kind==='spell'?'spell':'effect'}" data-action="stack-inspect" data-stack-id="${h(v.id)}" title="${h((v.resolving?'Resolving':i===0?'Resolves next':'Then '+(i+1))+': '+v.label)}" aria-label="${h(v.label)}"><img src="${h(asset(d.image))}" alt="${h(d.name)}"><span class="stack-kind">${v.resolving?'Resolving':v.kind==='spell'?'Spell':'Effect'} ${!v.resolving?i+1:''}</span></button>${button('↪','stack-hook',`data-stack-id="${h(v.id)}" title="Before / after resolution shortcut" aria-label="Configure shortcut for ${h(v.label)}"`,'stack-hook')}</div>`;}).join('')}</div><div class="stack-controls">${button('Resolve','resolve',s.pending?'disabled':'','primary')}${button('All','resolve-all',s.pending?'disabled':'')}${button('Pass','pass',s.pending?'disabled':'')}<label title="Keep priority so you can respond"><input type="checkbox" data-setting="holdPriority" ${s.settings.holdPriority?'checked':''}> Hold</label></div>`;
  return floating('stack','Stack',body,`<span class="stack-legend" title="Gold border: spell · teal border: ability/effect">${entries.length}</span>`,'stack-window');
}
export function inspectorPopup({g,ui,registry,prefs}){
  const o=g.object(ui.inspected);const d=o?g.definition(o):(ui.inspectDefinition?registry.get(ui.inspectDefinition):null);if(!d)return '';
  const c=o?g.characteristics(o):d,mod=o?g.module(o):registry.module(d.id);
  const abilities=o?g.abilities(o):[],isLand=c.types.includes('Land'),cast=o?g.castingPermissions(o,isLand).length>0:false;
  const waiting=!!g.state.pending,payment=['payment','effectPayment'].includes(g.state.pending?.kind);
  const body=`<div class="inspect-grid">${button(`<img src="${h(asset(o?.face&&d.backImage?d.backImage:d.image))}" alt="${h(d.name)}">`,'zoom',`data-card-id="${h(d.id)}" title="Enlarge card"`,'inspect-art')}<div class="inspect-actions"><div class="mana-cost">${manaText(c.manaCost||d.manaCost)}</div>${c.types.includes('Creature')?`<b class="stat">${c.power}/${c.toughness}</b>`:''}${ui.stackLabel?`<p class="effect-label">${h(ui.stackLabel)}</p>`:''}${cast?button(isLand?'Play land':'Cast','cast',`data-id="${h(o.id)}" ${waiting?'disabled':''}`,'primary'):''}${mod.plot&&o?.zone==='hand'?button('Plot','plot',`data-id="${h(o.id)}" ${waiting?'disabled':''}`):''}${abilities.map(a=>{const unavailable=(a.tap&&(o.tapped||g.isSick(o)))||(waiting&&(!payment||!a.mana));return button(h(a.label||a.id),'ability',`data-id="${h(o.id)}" data-ability="${h(a.id)}" ${unavailable?'disabled':''} title="${h(a.tap&&o.tapped?'Already tapped':a.tap&&g.isSick(o)?'Summoning sickness':a.mana?'Mana ability':a.label||a.id)}"`,'ability');}).join('')}${!cast&&!abilities.length?'<small>No activated action here.</small>':''}</div></div>${o?modePolicies(g,o,prefs):''}<details class="rules-text"><summary>Rules text</summary><div class="oracle">${h(d.oracleText)}</div></details><details><summary>Rulings <small>${d.rulings?.length||0}</small></summary>${(d.rulings||[]).map(r=>`<p>${h(r.comment)}</p>`).join('')||'<p>No additional rulings.</p>'}</details>${o?optionalPolicies(g,o):''}${o?playerPolicies(g,o,prefs,ui):''}`;
  return floating('inspector',d.name,body,tool('close','close-inspector'),'inspector-window');
}
function modePolicies(g,o,prefs){
  const rulesId=o.copy?.rulesId||o.cardId,module=g.module(o),definitions=[...(module.triggers||[]),...(module.activated||[])].filter(def=>def.modePreference);
  if(!definitions.length)return '';
  return `<div class="mode-preferences">${definitions.map(def=>{const meta=def.modePreference,key=`${rulesId}/${def.id}/${meta.key}`,value=prefs.modeDefaults?.[key]||'ASK';return `<div class="mode-pref-row"><span title="Always use this mode until you switch back to Ask. A current trigger can still use Modes to choose differently once.">${h(meta.label||def.label||'Default mode')}</span><div class="mode-pref-buttons">${button('Ask','mode-default',`data-mode-key="${h(key)}" data-mode-value="ASK" title="Ask every time"`,value==='ASK'?'active':'')}${(meta.options||[]).map(option=>button(h(option.label||option.value),'mode-default',`data-mode-key="${h(key)}" data-mode-value="${h(option.value)}" title="Always choose ${h(option.label||option.value)}"`,value===option.value?'active':'')).join('')}</div></div>`;}).join('')}</div>`;
}
function optionalPolicies(g,o){
  const keys=(g.module(o).triggers||[]).filter(t=>t.optional).map(t=>({id:t.id,label:t.label||t.id}));
  if(g.definition(o).name==='Tireless Provisioner')keys.push({id:'token-kind',label:'Landfall token',token:true});
  if(!keys.length)return '';
  return `<details class="policies"><summary>Optional effects</summary>${keys.map(k=>{const key=`${o.copy?.rulesId||o.cardId}/${k.id}`,value=g.state.optionalPreferences[key]||(k.token?'Treasure':'ASK');return `<label>${h(k.label)}<select data-policy="${h(key)}">${(k.token?['ASK','Treasure','Food']:['ASK','YES','NO']).map(v=>`<option ${v===value?'selected':''}>${v}</option>`).join('')}</select></label>`;}).join('')}</details>`;
}
function playerPolicies(g,o,prefs,ui){
 const context=g.context(o),definitions=[...(g.module(o).activated||[]),...(g.module(o).triggers||[]),...(g.module(o).spell?[{...g.module(o).spell,id:'spell'}]:[])];
 const rows=[];
 for(const d of definitions){let specs=[];try{specs=typeof d.inputs==='function'?d.inputs(g,o,context):d.inputs||[];}catch{}
  for(const spec of specs.filter(s=>s.type==='player')){
   const key=`${context.sourceCardId}/${d.id}/${spec.key}`,value=prefs.playerDefaults?.[key];
   rows.push(`<div class="player-policy"><small>${h(d.label||d.id)} — target player</small><div class="mode-pref-buttons">${[['ASK','Ask'],[0,'You'],[1,'OP1'],[2,'OP2'],[3,'OP3'],['ONCE','Choose once']].map(([v,label])=>button(label,'player-default',`data-player-key="${h(key)}" data-player-value="${v}" title="${v==='ONCE'?'Ignore the saved player for the next activation only':'Default target: '+label}"`,(v==='ASK'?value==null:v==='ONCE'?ui.askOnce?.[key]:value===v)?'active':'')).join('')}</div></div>`);
  }
 }
 return rows.length?`<div class="player-policies">${rows.join('')}</div>`:'';
}
export function decisionPopup(ctx){
 const p=ctx.g.state.pending;if(!p)return '';
 if(isManaColorChoice(p))return manaChoiceHTML(p);
 const draft=ctx.g.state.actionDraft,definition=draft?ctx.g.draftDefinition(draft):null,mode=definition?.modePreference;
 let revise=draft&&p.kind==='draft'&&mode&&p.key!==mode.key&&Object.hasOwn(draft.context.inputs,mode.key)
    ?button('Modes','revise-choice',`data-key="${h(mode.key)}" title="Choose a different mode for this trigger only"`,'quiet'):'';
 if(draft&&p.kind==='draft')for(const spec of ctx.g.inputSpecs(draft))if(spec.type==='player'&&p.key!==spec.key&&Object.hasOwn(draft.context.inputs,spec.key))revise+=button('Player','revise-choice',`data-key="${h(spec.key)}" title="Choose another player this time"`,'quiet');
 let body;
 if(p.ordered){
  const options=p.options||[];
  body=`<p class="muted">${p.kind==='triggerOrder'?'First row resolves first.':'First row is the top card.'} Drag rows or use the arrows.</p><div class="ordered-list" data-scroll="ordered">${ctx.ui.choice.map((id,i)=>`<div class="choice-row" draggable="true" data-order-id="${h(id)}"><span class="order-grip" title="Drag to reorder">⠿</span><span class="ordinal">${i+1}</span><span class="order-label">${h(options.find(o=>o.value===id)?.label||ctx.g.definition(id).name)}</span>${button('⇈','order-edge',`data-index="${i}" data-edge="top" title="Move to top" aria-label="Move item ${i+1} to top" ${i===0?'disabled':''}`)}${button('↑','order',`data-index="${i}" data-direction="-1" aria-label="Move item ${i+1} earlier" ${i===0?'disabled':''}`)}${button('↓','order',`data-index="${i}" data-direction="1" aria-label="Move item ${i+1} later" ${i===ctx.ui.choice.length-1?'disabled':''}`)}${button('⇊','order-edge',`data-index="${i}" data-edge="bottom" title="Move to bottom" aria-label="Move item ${i+1} to bottom" ${i===ctx.ui.choice.length-1?'disabled':''}`)}</div>`).join('')}</div><div class="order-footer">${button(p.kind==='triggerOrder'?'Confirm resolution order':'Confirm card order','confirm-choice','','primary')}</div>`;
 }else body=decisionHTML(ctx);
 if(!p.ordered&&(p.candidates||p.ids))body+=`<label class="auto-accept"><input type="checkbox" data-auto-accept ${ctx.prefs.autoAccept?'checked':''}> Auto-accept completed selections</label>`;
 let html=floating('decision',p.label,body,revise+tool('close','cancel','title="Cancel / decline (Escape)" aria-label="Cancel decision"'),'decision-window'+(p.ordered?' ordering-window':''));
 if(p.ordered)html=html.replace('data-floating="decision"','data-floating="decision" data-resizable="true"').replace('</section>','<div class="popup-resize" data-resize-popup="decision" title="Resize ordering window" role="separator" aria-label="Resize ordering window" tabindex="0"></div></section>');
 return html;
}
export function openingPopup({g}){
  if(g.state.started||g.state.pending)return '';
  return `<section class="opening-prompt" aria-label="Opening hand"><span>Opening hand${g.state.mulligans?' · mulligan '+g.state.mulligans:''}</span>${button('Mulligan','mulligan')}${button('Keep','keep','','primary')}</section>`;
}
export function menuBody({g,saveStatus}){
  const items=[['New test','new'],['Laboratory','labs'],['Cards','cards'],['Deck editor','deck'],['Save / import','save'],['Settings','settings'],['Action log','log'],['Notes','notes'],['Guide','guide'],['Sequences','sequences'],['Automations','automation']];
  return `<div class="app-menu-grid">${items.map(([label,name])=>button(label,'dialog',`data-dialog="${name}"`)).join('')}</div><div class="menu-undo">${button('Undo','undo',!g.cursor&&!g.transaction?'disabled':'')}${button('Redo','redo',g.cursor>=g.history.length||g.transaction?'disabled':'')}<small>Backspace: undo · Esc: cancel</small></div><label class="menu-preference"><input type="checkbox" data-setting="holdPriority" ${g.state.settings.holdPriority?'checked':''}> Hold priority</label><p class="save-status ${saveStatus.error?'error':''}" id="save-status">${h(saveStatus.text)}</p>`;
}
