from ui_acceptance_support import *

def opening(p):
 check('release uses compact tabletop controller',p.evaluate('astra.version')=='1.4.0')
 check('hold priority defaults off; reserve access defaults on',not state(p,'state.settings.holdPriority') and state(p,'state.reserveAccess'))
 check('default active 92 + hand 7, reserve 20, commander 1',state(p,'state.zones.libraryActive.length')==92 and state(p,'state.zones.hand.length')==7 and state(p,'state.zones.libraryReserve.length')==20 and state(p,'state.zones.command.length')==1)
 check('one small toolbar replaces the header and permanent inspector',p.locator('.app-header,.inspector-pane,.stack-panel,.status-bar,.hand-header,.card-name').count()==0)
 check('empty stack and inspector are hidden',p.locator('.stack-window,.inspector-window').count()==0)
 check('left rail is approximately deck width',p.locator('.rail').bounding_box()['width']==100)
 check('real Magic card back is loaded',p.locator('.deck-back img').evaluate('(e)=>e.complete&&e.naturalWidth>0'))
 check('hand count and land plays have tooltips',p.locator('.library-icons [title="Cards in hand"]').count()==1 and p.locator('.library-icons [title="Land plays"]').count()==1)
 check('six short mana rows and one row per opponent',p.locator('.mana-row').count()==6 and p.locator('.opponents-totals .total-row').count()==3)
 shot(p,'01-compact-opening.png')
 click(p,'mulligan','.opening-prompt');click(p,'keep','.opening-prompt');settle(p)
 check('first multiplayer mulligan is free',state(p,'state.zones.hand.length')==7)
 click(p,'phase',extra='[data-step="main1"]');settle(p)
 check('phase navigation performs first draw',state(p,'state.step')=='main1' and state(p,'state.zones.hand.length')==8)
 click(p,'next-player');settle(p)
 check('next turn advances to highlighted opponent 1',state(p,'state.activePlayer')==1 and p.locator('[data-action=opponent][data-player="1"]').evaluate('(e)=>e.classList.contains("active")'))
 click(p,'opponent',extra='[data-player="2"]');settle(p);check('direct opponent 2 turn control',state(p,'state.activePlayer')==2)
 click(p,'opponent',extra='[data-player="3"]');settle(p);check('direct opponent 3 turn control',state(p,'state.activePlayer')==3)
 click(p,'next-turn');settle(p);check('your next turn advances back to own main phase',state(p,'state.activePlayer')==0 and state(p,'state.turnNumber')==2)
 for attempt in range(2):
  menu(p,'new');p.locator('#new-seed').fill('ui-repeatable-seed');click(p,'start-new','.modal')
  current=state(p,'state.initialDeck.activeOrder')
  if not attempt:original=current
  else:check('same seed reproduces active library through actual New test dialog',current==original)
 click(p,'mulligan','.opening-prompt');click(p,'mulligan','.opening-prompt');click(p,'keep','.opening-prompt');settle(p)
 check('second London mulligan selects one bottom card and keeps six',state(p,'state.zones.hand.length')==6)

def mana(p):
 fixture(p,'mana');r=obj(p,'Razortide Bridge');b=card(p,r['id'],'battlefield').bounding_box();x,y=b['x']+b['width']*.65,b['y']+b['height']*.45;p.mouse.click(x,y)
 check('dual land opens only a tiny symbol palette',p.locator('.mana-window .mana-choice').count()==2 and p.locator('.mana-window').bounding_box()['height']<=55)
 check('palette has no visible text or payment controls',p.locator('.mana-window').inner_text().strip()=='' and p.locator('.mana-window .float-header,.mana-window input').count()==0)
 popup=p.locator('.mana-window').bounding_box();check('mana palette opens beside the clicked source',abs(popup['x']-x)<130 and abs(popup['y']-y)<80)
 check('mana colors have real local vector symbols',p.locator('.mana-choice svg').count()==2)
 shot(p,'02-mana-symbols.png');choose_option(p,'U')
 check('one symbol click taps source and immediately adds blue',obj(p,'Razortide Bridge')['tapped'] and state(p,'state.players[0].mana.U')==1 and pending(p) is None)
 rb=card(p,r['id'],'battlefield').bounding_box();check('tapped card is physically sideways',rb['width']>rb['height'] and abs(rb['width']-b['height'])<.1)
 check('clockwise tapping keeps the physical bottom-right at the upright bottom-left anchor',abs(rb['x']-b['x'])<.1 and abs(rb['y']+rb['height']-b['y']-b['height'])<.1)
 card(p,r['id'],'battlefield').click();check('tapped source cannot open a mana-color choice',pending(p) is None and p.locator('.mana-window').count()==0)
 check('tapped mana ability is disabled in inspector',p.locator('.inspector-window [data-action=ability]').first.is_disabled())
 card(p,r['id'],'battlefield').click();check('second click on inspected card closes inspector',p.locator('.inspector-window').count()==0)
 a=obj(p,'Mox Amber');card(p,a['id'],'battlefield').click();q=pending(p)
 check('Amber palette offers only colors among controlled legends',{o['value'] for o in q['options']}=={'G','U'})
 p.keyboard.press('Escape');check('Escape cancels color choice without tapping Amber',not obj(p,'Mox Amber')['tapped'] and pending(p) is None)
 card(p,a['id'],'battlefield').click();choose_option(p,'G');check('Amber commits selected green mana',obj(p,'Mox Amber')['tapped'] and state(p,'state.players[0].mana.G')==1)
 o=obj(p,'Mox Opal');card(p,o['id'],'battlefield').click();check('metalcraft Opal palette offers five colors',p.locator('.mana-choice').count()==5)
 choose_option(p,'R');check('Opal commits selected red mana',obj(p,'Mox Opal')['tapped'] and state(p,'state.players[0].mana.R')==1)
 card(p,o['id'],'battlefield').click();check('already-tapped Opal never asks for a color',pending(p) is None)
 fixture(p,'amber-no-legend');card(p,obj(p,'Mox Amber')['id'],'battlefield').click();check('Amber without qualifying legend has no selectable mana ability',pending(p) is None and not obj(p,'Mox Amber')['tapped'])
 fixture(p,'amber-no-legend');card(p,obj(p,'Mox Opal')['id'],'battlefield').click();check('Opal without metalcraft has no selectable mana ability',pending(p) is None and not obj(p,'Mox Opal')['tapped'])

def payments(p):
 fixture(p,'payments');cast(p,'The One Ring');check('cast pauses for explicit allocation without consuming the hand card',pending(p)['kind']=='payment' and obj(p,'The One Ring','hand'))
 before=checksum(p);p.locator('#pay-C').fill('0');click(p,'pay','[data-floating="decision"]');check('invalid payment is rejected atomically',checksum(p)==before)
 # Close inspection, but leave payment open; mana sources stay clickable.
 if p.locator('.inspector-window').count():click(p,'close-inspector')
 amber=obj(p,'Mox Amber');card(p,amber['id'],'battlefield').click();check('clicking Amber during casting opens the same tiny color palette',p.locator('.mana-window').count()==1)
 choose_option(p,'U');check('mana choice returns to parent payment rather than finishing/cancelling cast',pending(p)['kind']=='payment' and state(p,'state.players[0].mana.U')==1)
 vault=obj(p,'Mana Vault');card(p,vault['id'],'battlefield').click();check('direct mana source remains usable during payment',pending(p)['kind']=='payment' and state(p,'state.players[0].mana.C')==3)
 shot(p,'03-payment-with-table.png');pay(p);p.wait_for_function("()=>Object.values(astra.engine.state.instances).some(o=>o.zone==='battlefield'&&astra.engine.definition(o).name==='The One Ring')");p.wait_for_function('()=>!astra.engine.state.stack.length&&!astra.engine.state.pending')
 check('default automatic resolution casts and resolves Ring without extra Resolve clicks',obj(p,'The One Ring','battlefield') is not None)
 check('resolved empty stack popup closes itself',p.locator('.stack-window').count()==0)
 before=checksum(p);p.keyboard.press('Backspace');check('Backspace undoes outside a text field',checksum(p)!=before)
 p.keyboard.press('Control+Shift+z');check('redo shortcut restores exact resolved state',checksum(p)==before)
 fixture(p,'payments');cast(p,'Walking Atlas');p.keyboard.press('Escape');check('Escape cancels whole unpaid cast',pending(p) is None and obj(p,'Walking Atlas','hand'))
 hold(p,True);cast(p,'Walking Atlas')
 if p.locator('.inspector-window').count():click(p,'close-inspector')
 card(p,obj(p,"Mishra's Workshop")['id'],'battlefield').click();check('restricted mana source works while paying',state(p,'state.players[0].restrictedMana.length')==1)
 pay(p);check('hold priority leaves a spell image on stack',p.locator('.stack-card.spell img').count()==1 and obj(p,'Walking Atlas','stackCards'))
 shot(p,'04-spell-stack.png');click(p,'stack-inspect','.stack-window');check('stack image opens card/effect inspector',p.locator('.inspector-window').is_visible())
 click(p,'resolve','.stack-window');check('manual Resolve empties stack and enters permanent',obj(p,'Walking Atlas','battlefield') is not None and p.locator('.stack-window').count()==0)
 click(p,'dialog',extra='[data-dialog=mana]');check('restricted mana detail opens from hidden dialog',p.locator('#modal-title').inner_text()=='Restricted mana');close(p)
