from ui_acceptance_support import *

def access(p,name,zone='battlefield'):
 o=obj(p,name,zone);assert o,name+' missing'
 return p.locator('[data-surface="'+zone+'"] [data-action="card-abilities"][data-id="'+o['id']+'"]')

def vault_ability_access(p):
 fixture(p,'vault-access');hold(p,True);before=checksum(p)
 check('Treasure Vault has a visible separate Abilities button',access(p,'Treasure Vault').is_visible())
 access(p,'Treasure Vault').click()
 check('ordinary left-click on Abilities opens Treasure Vault without tapping or adding mana',p.locator('.inspector-window').count()==1 and checksum(p)==before)
 check('Treasure Vault inspector exposes both mana and Create X Treasures',p.locator('.inspector-window [data-ability="mana"]').count()==1 and p.locator('.inspector-window [data-ability="treasures"]').is_enabled())
 shot(p,'21-treasure-vault-abilities.png')
 access(p,'Treasure Vault').click();check('clicking the same Abilities control closes inspection with no game action',p.locator('.inspector-window').count()==0 and checksum(p)==before)
 access(p,'Treasure Vault').focus();p.keyboard.press('Enter')
 check('Abilities control also works using keyboard activation without tapping',p.locator('.inspector-window [data-ability="treasures"]').is_enabled() and checksum(p)==before)
 click(p,'ability','.inspector-window','[data-ability="treasures"]')
 check('Treasure Vault X choice is reachable without spending its tap on mana',pending(p)['type']=='number' and not obj(p,'Treasure Vault')['tapped'])
 p.locator('#number-choice').fill('3');click(p,'confirm-number','[data-floating="decision"]')
 check('double-X cost asks for six mana before sacrificing the Vault',p.locator('#pay-C').input_value()=='6' and obj(p,'Treasure Vault','battlefield') is not None)
 p.keyboard.press('Escape');check('cancelling special activation preserves land and resources',checksum(p)==before and p.locator('.inspector-window').count()==1)
 click(p,'ability','.inspector-window','[data-ability="treasures"]');p.locator('#number-choice').fill('3');click(p,'confirm-number','[data-floating="decision"]');pay(p)
 check('paying special activation sacrifices Vault and closes inspector only on commitment',obj(p,'Treasure Vault','graveyard') is not None and state(p,'state.players[0].mana.C')==0 and p.locator('.inspector-window').count()==0)
 click(p,'resolve','.stack-window')
 check('Treasure Vault special activation creates exactly three real Treasure tokens',state(p,"controlled().filter(o=>o.token&&astra.engine.definition(o).name==='Treasure').length")==3)
 check('special-ability flow never enables manual controls',not state(p,'state.settings.manualControls'))
 p.keyboard.press('Backspace');p.keyboard.press('Backspace')
 check('undo resolution and activation restores Vault and all six mana',checksum(p)==before)
 vault=obj(p,'Treasure Vault');card(p,vault['id'],'battlefield').click()
 check('clicking Vault artwork opens its choices without an accidental mana activation',not obj(p,'Treasure Vault')['tapped'] and state(p,'state.players[0].mana.C')==6 and pending(p) is None and p.locator('.inspector-window').count()==1)
 click(p,'ability','.inspector-window','[data-ability=mana]');access(p,'Treasure Vault').click()
 check('already tapped Vault still inspects but cannot illegally activate either tap ability',p.locator('.inspector-window [data-ability="treasures"]').is_disabled() and p.locator('.inspector-window [data-ability="mana"]').is_disabled())
 check('single-purpose mana land does not get an unnecessary action badge',p.locator('[data-surface=battlefield] [data-card="'+obj(p,'Ancient Den')['id']+'"] [data-action=card-abilities]').count()==0)

def special_lands_access(p):
 fixture(p,'special-land-access');hold(p,True)
 for name,ability_id in [('Oboro, Palace in the Clouds','return'),('Buried Ruin','recover'),('Fomori Vault','vault')]:
  before=checksum(p);access(p,name).click()
  check(name+' special ability is reachable by its visible left-click control',p.locator('.inspector-window [data-ability="'+ability_id+'"]').is_enabled() and checksum(p)==before)
  access(p,name).click()
 # Oboro can still return to hand even after its mana ability used its tap.
 oboro=obj(p,'Oboro, Palace in the Clouds');card(p,oboro['id'],'battlefield').click();click(p,'ability','.inspector-window','[data-ability=mana]');access(p,'Oboro, Palace in the Clouds').click()
 check('tapped Oboro still exposes its non-tap return ability',p.locator('.inspector-window [data-ability="return"]').is_enabled())
 click(p,'ability','.inspector-window','[data-ability="return"]');pay(p);click(p,'resolve','.stack-window')
 check('Oboro return resolves from inspector without requiring an illegal untap',obj(p,'Oboro, Palace in the Clouds','hand') is not None and state(p,'state.players[0].mana.U')==1)
 access(p,'Buried Ruin').click();click(p,'ability','.inspector-window','[data-ability="recover"]');choose_cards(p,[obj(p,'Mox Amber','graveyard')['id']]);pay(p);click(p,'resolve','.stack-window')
 check('Buried Ruin can sacrifice to recover an artifact using the same control',obj(p,'Buried Ruin','graveyard') is not None and obj(p,'Mox Amber','hand') is not None)
 access(p,'Fomori Vault').click();click(p,'ability','.inspector-window','[data-ability="vault"]');choose_cards(p,[obj(p,'Explore','hand')['id']]);pay(p);click(p,'resolve','.stack-window')
 choose_cards(p,[obj(p,'Walking Atlas','libraryActive')['id']]);settle(p)
 check('Fomori Vault discard and library ability is reachable without taking its mana action',obj(p,'Explore','graveyard') is not None and obj(p,'Walking Atlas','hand') is not None and obj(p,'Fomori Vault')['tapped'])
 fixture(p,'saga-access');hold(p,True);access(p,"Urza's Saga").click();click(p,'ability','.inspector-window','[data-ability="construct"]');pay(p);click(p,'resolve','.stack-window')
 check('chapter-granted Saga Construct ability is reachable from the live action control',obj(p,'Construct','battlefield') is not None and obj(p,"Urza's Saga")['tapped'])
 fixture(p,'monolith-access');hold(p,True);access(p,'Grim Monolith').click()
 check('tapped Grim Monolith can open its untap ability while mana is disabled',p.locator('.inspector-window [data-ability="untap"]').is_enabled() and p.locator('.inspector-window [data-ability="mana"]').is_disabled())
 click(p,'ability','.inspector-window','[data-ability="untap"]');pay(p);click(p,'resolve','.stack-window')
 check('non-land mana permanent untap action pays and resolves correctly',not obj(p,'Grim Monolith')['tapped'] and state(p,'state.players[0].mana.C')==0)

def granted_ability_access(p):
 fixture(p,'granted-access');hold(p,True);access(p,'Ancient Den').click()
 check('a plain mana land receives the same control for a granted Stash ability',p.locator('.inspector-window [data-ability="stash-treasure"]').is_enabled())
 click(p,'ability','.inspector-window','[data-ability="stash-treasure"]');click(p,'resolve','.stack-window')
 check('granted ability creates a Treasure instead of choosing printed land mana',obj(p,'Treasure','battlefield') is not None and state(p,'state.players[0].mana.W')==0)
 activate(p,'Krark-Clan Ironworks','sacrifice');choose_cards(p,[obj(p,"Bootleggers' Stash")['id']]);settle(p)
 check('removing granting permanent removes now-redundant land action control',access(p,'Ancient Den').count()==0)
 fixture(p,'vault-payment');hold(p,True);cast(p,'Walking Atlas');before=checksum(p);access(p,'Treasure Vault').click()
 check('ability inspection can open during payment without disturbing the pending spell',pending(p)['kind']=='payment' and checksum(p)==before)
 check('payment inspection enables only legal mana actions, not a non-mana Vault sacrifice',p.locator('.inspector-window [data-ability="mana"]').is_enabled() and p.locator('.inspector-window [data-ability="treasures"]').is_disabled())
 click(p,'ability','.inspector-window','[data-ability="mana"]')
 check('chosen mana activation returns to original spell payment',pending(p)['kind']=='payment' and obj(p,'Treasure Vault')['tapped'] and state(p,'state.players[0].mana.C')==1)
 card(p,obj(p,'Ancient Den')['id'],'battlefield').click();pay(p);click(p,'resolve','.stack-window')
 check('spell completes after mixing inspected and quick-click mana abilities',obj(p,'Walking Atlas','battlefield') is not None and state(p,'state.players[0].mana.C')==0 and state(p,'state.players[0].mana.W')==0)

def ability_button_geometry(p):
 fixture(p,'ability-layers');hold(p,True);before=checksum(p);badge=access(p,'Treasure Vault').bounding_box()
 drag(p,badge['x']+badge['width']/2,badge['y']+badge['height']/2,badge['x']-65,badge['y']+50)
 check('dragging off an Abilities button cancels it without moving or tapping the card',checksum(p)==before and p.locator('.inspector-window').count()==0 and p.locator('.drag-ghost').count()==0)
 # Arrange overlapping rectangles through actual drag gestures, not state injection.
 vault=place(p,'Treasure Vault',340,190);b=card(p,vault,'battlefield').bounding_box();den=place(p,'Ancient Den',b['x']+b['width']*.45,b['y']-10)
 badge=access(p,'Treasure Vault').bounding_box();p.mouse.move(b['x']+5,b['y']+b['height']*.7);p.wait_for_timeout(80)
 p.mouse.move(badge['x']+badge['width']/2,badge['y']+badge['height']/2);p.wait_for_timeout(80);p.mouse.down();p.mouse.up()
 check('hover elevation cannot steal upper-card click through a lower card ability control',obj(p,'Ancient Den')['tapped'] and not obj(p,'Treasure Vault')['tapped'] and p.locator('.inspector-window').count()==0)
 # A real touchscreen uses the same route, with an enlarged but compact badge.
 context=p.context.browser.new_context(viewport={'width':1024,'height':768},has_touch=True,is_mobile=True)
 q=context.new_page();q.on('pageerror',lambda e:errors.append(str(e)));q.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
 try:
  if args.memory:q.set_content(html,wait_until='load')
  else:q.goto(args.url,wait_until='load')
  q.wait_for_function('()=>window.astra?.engine');fixture(q,'vault-access');before=checksum(q)
  r=access(q,'Treasure Vault').bounding_box();q.touchscreen.tap(r['x']+r['width']/2,r['y']+r['height']/2)
  check('touch-only Abilities button opens Vault without a right-click or unintended mana',q.locator('.inspector-window [data-ability="treasures"]').is_visible() and checksum(q)==before)
  q.touchscreen.tap(r['x']+r['width']/2,r['y']+r['height']/2)
  check('second touchscreen tap closes exactly once without a compatibility-click reopen',q.locator('.inspector-window').count()==0 and checksum(q)==before)
  land=card(q,obj(q,'Treasure Vault')['id'],'battlefield').bounding_box()
  q.touchscreen.tap(land['x']+land['width']/2,land['y']+land['height']/2)
  check('touchscreen Vault face opens utility choices without an unintended activation',not obj(q,'Treasure Vault')['tapped'] and state(q,'state.players[0].mana.C')==6 and q.locator('.inspector-window').count()==1)
  click(q,'ability','.inspector-window','[data-ability=mana]');check('touch-inspected explicit mana activates exactly once',obj(q,'Treasure Vault')['tapped'] and state(q,'state.players[0].mana.C')==7)
 finally:context.close()
