from ui_acceptance_support import *

def inspector_choices(p):
    fixture(p,'inspector-actions')
    # Repeatable KCI activation keeps the inspector open when another artifact pays the cost.
    inspect(p,'Krark-Clan Ironworks')
    click(p,'ability','.inspector-window','[data-ability="sacrifice"]')
    choose_cards(p,[obj(p,'Ancient Den')['id']])
    p.wait_for_function("()=>!astra.engine.state.pending&&!astra.engine.state.actionDraft")
    check('repeatable KCI activation keeps inspector open',p.locator('.inspector-window').count()==1 and 'Krark-Clan Ironworks' in p.locator('.inspector-window').inner_text())
    # Same repeatable ability becomes single-use in practice when KCI itself is the sacrifice.
    click(p,'ability','.inspector-window','[data-ability="sacrifice"]')
    choose_cards(p,[obj(p,'Krark-Clan Ironworks')['id']])
    p.wait_for_function("()=>!astra.engine.state.pending&&!astra.engine.state.actionDraft")
    check('inspector closes when its source leaves the inspected zone',p.locator('.inspector-window').count()==0 and obj(p,'Krark-Clan Ironworks','graveyard') is not None)

    fixture(p,'inspector-actions')
    inspect(p,'Scene of the Crime')
    click(p,'ability','.inspector-window','[data-ability="filter"]')
    q=pending(p)
    check('Scene asks for creature paying additional tap cost before mana color',q and q.get('key')=='tapped' and q.get('cost') is True and p.locator('.mana-window').count()==0)
    p.keyboard.press('Escape')
    check('cancelling single-use activation leaves inspector open',p.locator('.inspector-window').count()==1 and not obj(p,'Scene of the Crime')['tapped'])
    click(p,'ability','.inspector-window','[data-ability="filter"]')
    choose_cards(p,[obj(p,'Walking Atlas')['id']])
    q=pending(p)
    check('Scene asks for produced color only after additional cost selection',q and q.get('key')=='color' and p.locator('.mana-window .mana-choice').count()==5)
    choose_option(p,'G')
    p.wait_for_function("()=>!astra.engine.state.pending&&!astra.engine.state.actionDraft")
    check('completed tap ability closes inspector',p.locator('.inspector-window').count()==0 and obj(p,'Scene of the Crime')['tapped'] and obj(p,'Walking Atlas')['tapped'] and state(p,'state.players[0].mana.G')==1)

    fixture(p,'raft-modes');hold(p,True)
    inspect(p,'Elven Raft-Steerer')
    check('modal trigger exposes easy Ask and persistent mode buttons',p.locator('.mode-pref-buttons [data-action="mode-default"]').count()==3)
    p.locator('.mode-pref-buttons [data-mode-value="untap"]').click()
    key=p.evaluate("astra.registry.get('Elven Raft-Steerer').id+'/steer/mode'")
    check('Raft-Steerer always-mode preference is saved',p.evaluate('(k)=>astra.prefs.modeDefaults[k]',key)=='untap')
    click(p,'close-inspector')
    cast(p,'Ancient Den');p.wait_for_function("()=>astra.engine.state.stack.length||astra.engine.state.pending")
    if state(p,'state.stack.length'):click(p,'resolve','.stack-window')
    p.wait_for_function("()=>astra.engine.state.pending?.key==='target'")
    check('saved Raft-Steerer mode skips repeated mode prompt',state(p,'state.actionDraft.context.inputs.mode')=='untap' and obj(p,'Walking Atlas')['id'] in pending(p)['candidates'])
    check('dependent choice offers a one-trigger Modes override',p.locator('[data-floating="decision"] [data-action="revise-choice"]').count()==1)
    click(p,'revise-choice','[data-floating="decision"]')
    p.wait_for_function("()=>astra.engine.state.pending?.key==='mode'")
    check('Modes returns this trigger to its original mode choices',set(o['value'] for o in pending(p)['options'])=={'tap','untap'})
    choose_option(p,'tap')
    p.wait_for_function("()=>astra.engine.state.pending?.key==='target'")
    enemy=obj(p,'Krang, Master Mind')
    check('one-trigger override rebuilds dependent targets',pending(p)['candidates']==[enemy['id']])
    choose_cards(p,[enemy['id']]);settle(p)
    check('one-trigger override resolves without changing saved default',obj(p,'Krang, Master Mind')['tapped'] and p.evaluate('(k)=>astra.prefs.modeDefaults[k]',key)=='untap')

    # Next trigger returns to the saved default, proving the override was one-shot.
    cast(p,'Tree of Tales');p.wait_for_function("()=>astra.engine.state.stack.length||astra.engine.state.pending")
    if state(p,'state.stack.length'):click(p,'resolve','.stack-window')
    p.wait_for_function("()=>astra.engine.state.pending?.key==='target'")
    check('next trigger returns to saved default mode',state(p,'state.actionDraft.context.inputs.mode')=='untap' and obj(p,'Walking Atlas')['id'] in pending(p)['candidates'])
    choose_cards(p,[obj(p,'Walking Atlas')['id']]);settle(p)
    inspect(p,'Elven Raft-Steerer')
    p.locator('.mode-pref-buttons [data-mode-value="ASK"]').click()
    check('mode preference turns off with one click',p.evaluate('(k)=>astra.prefs.modeDefaults[k] ?? null',key) is None)
    shot(p,'13-inspector-and-mode-default.png')
