import { Engine, parseDeck, COLORS, suggestPayment } from '../core/index.js';
import { createRegistry } from '../rules/index.js';
import { SessionStore } from './storage.js';
import { createLab } from './labs.js';
import { h, button, saveDownload, STEP_NAMES } from './components.js';
import { headerHTML, sidebarHTML, tableHTML, inspectorHTML, choiceOptions } from './views.js';
import { dialogHTML } from './dialogs.js';

const data=window.ASTRA_DATA,registry=createRegistry(data.cards),store=new SessionStore();
const root=document.getElementById('app'),overlay=document.getElementById('overlay');
const seed=()=>`astra-${new Date().toISOString().slice(0,10)}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`;
const ui={zone:'battlefield',inspected:null,inspectorTab:'inspect',selected:new Set(),selectMode:false,modal:null,previousModal:null,seed:seed(),deckText:data.deckText,deckReport:null,cardFilter:'',cardType:'',showDerived:false,zoomCard:null,backFace:false,pendingKey:null,choice:[],choiceFilter:'',number:0,payment:null,noteText:'',cardSize:innerWidth<600?100:110,canvasWidth:Math.max(260,innerWidth-(innerWidth>900?540:innerWidth>600?190:30)),attacks:{}};
let g,unsubscribe,saveTimer,gameSequence=0,rendering=false,ignoreClickUntil=0,drag=null;
const saveStatus={text:'Opening browser storage…',error:false};
const ctx=()=>({g,ui,registry,saveStatus});
const byId=id=>document.getElementById(id);
function toast(message,error=false){let el=byId('toast');if(el)el.remove();el=document.createElement('div');el.id='toast';el.className=`toast ${error?'error':''}`;el.setAttribute('role',error?'alert':'status');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),error?6500:3500);}
function updateSaveLabel(){const el=byId('save-status');if(el){el.textContent=saveStatus.text;el.style.color=saveStatus.error?'var(--red)':'';}}
async function saveNow(){if(!g)return;clearTimeout(saveTimer);const sequence=gameSequence,snapshot=g.exportSession();try{const at=await store.save(snapshot);if(sequence===gameSequence){saveStatus.text=`Autosaved ${new Date(at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;saveStatus.error=false;updateSaveLabel();}}catch(error){if(sequence===gameSequence){saveStatus.text=error.message;saveStatus.error=true;updateSaveLabel();}throw error;}}
function scheduleSave(){clearTimeout(saveTimer);saveStatus.text='Saving…';updateSaveLabel();saveTimer=setTimeout(()=>saveNow().catch(()=>{}),100);}
function useEngine(engine,save=true){unsubscribe?.();clearTimeout(saveTimer);g=engine;gameSequence++;ui.pendingKey=null;ui.selected.clear();ui.inspected=null;ui.zone='battlefield';ui.modal=null;ui.noteText='';unsubscribe=g.subscribe(()=>{try{render();}catch(error){rendering=false;toast(`Unable to refresh the view: ${error.message}`,true);console.error(error);}scheduleSave();});render();if(save)scheduleSave();}
function focusSnapshot(){const a=document.activeElement;return a?.id?{id:a.id,start:a.selectionStart,end:a.selectionEnd}:null;}
function restoreFocus(f){if(!f)return;const el=byId(f.id);if(!el)return;el.focus({preventScroll:true});if(typeof f.start==='number'&&typeof el.setSelectionRange==='function')try{el.setSelectionRange(f.start,f.end);}catch{}}
function prepareChoice(){const p=g.state.pending;const key=p?JSON.stringify([p.kind,p.key,p.label,p.source,p.candidates,p.options,g.state.resolving?.pc,g.state.actionDraft?.context?.inputs]):null;if(key===ui.pendingKey)return;ui.pendingKey=key;ui.choiceFilter='';ui.choice=p?.ordered?[...(p.candidates||choiceOptions(p).map(o=>o.value))]:[];ui.number=p?.min||0;ui.payment=['payment','effectPayment'].includes(p?.kind)?suggestPayment(p.cost,g.state.players[p.player||0],p.context)||{normal:{},tagged:[]}:null;}
function render(){if(!g||rendering)return;rendering=true;prepareChoice();const focus=focusSnapshot(),scroll=new Map([...document.querySelectorAll('[data-scroll]')].map(el=>[el.dataset.scroll,[el.scrollLeft,el.scrollTop]]));document.documentElement.style.setProperty('--card',`${ui.cardSize}px`);root.innerHTML=headerHTML(ctx())+`<div class="workspace">${sidebarHTML(ctx())}${tableHTML(ctx())}${inspectorHTML(ctx())}</div><footer class="status-bar"><span>SEED ${h(g.state.seed)} · ${g.cursor} actions${g.state.initialDeck.scenario?' · Laboratory fixture':''}</span><span id="save-status">${h(saveStatus.text)}</span><span>${h(g.state.rulesPack)} · Local rules · No runtime network</span></footer>`;renderModal(false);for(const el of document.querySelectorAll('[data-scroll]')){const xy=scroll.get(el.dataset.scroll);if(xy){el.scrollLeft=xy[0];el.scrollTop=xy[1];}}restoreFocus(focus);rendering=false;requestAnimationFrame(()=>{const width=byId('canvas')?.clientWidth;if(width&&Math.abs(width-ui.canvasWidth)>4&&!drag){ui.canvasWidth=width;render();}});}
function renderModal(preserve=true){const focus=preserve?focusSnapshot():null,scroll=overlay.querySelector('.modal-body')?.scrollTop||0;overlay.innerHTML=dialogHTML(ctx());document.body.classList.toggle('no-scroll',!!ui.modal);root.inert=!!ui.modal;if(preserve){const b=overlay.querySelector('.modal-body');if(b)b.scrollTop=scroll;restoreFocus(focus);}}
function openDialog(name){ui.modal=name;if(name==='new')ui.seed=seed();renderModal();requestAnimationFrame(()=>overlay.querySelector('input:not([type=checkbox]),textarea,button')?.focus());}
function run(action){const result=g.perform(action);if(!result.ok)toast(result.error.message,true);else if(!g.state.settings.holdPriority&&!g.state.pending&&!g.state.actionDraft&&!g.state.resolving&&['CAST_SPELL','ACTIVATE_ABILITY','CHOOSE','SPECIAL_ACTION'].includes(action.type)&&g.state.stack.length){const resolved=g.perform({type:'RESOLVE_ALL'});if(!resolved.ok)toast(resolved.error.message,true);}return result;}
function choose(value){return run({type:'CHOOSE',value,remember:!!byId('remember-choice')?.checked});}
function inspect(id){ui.inspected=id;ui.inspectorTab='inspect';render();if(innerWidth<900)document.querySelector('.inspector-tabs')?.scrollIntoView({behavior:'smooth',block:'start'});}
function toggleChoice(id){const p=g.state.pending,ids=p?.candidates||p?.ids||[];if(!ids.includes(id))return false;if(ui.choice.includes(id))ui.choice=ui.choice.filter(v=>v!==id);else if((p.max||1)===1)ui.choice=[id];else if(ui.choice.length<(p.max||1))ui.choice.push(id);else{toast(`Choose at most ${p.max} cards.`,true);return true;}render();return true;}
function auditDeck(){const parsed=parseDeck(ui.deckText),report=registry.report(parsed.records),errors=parsed.errors.map(e=>`Line ${e.line}: ${e.message}`);let construction=null;if(!errors.length&&!report.missing.length)try{const trial=Engine.create(registry,parsed.records,'deck-audit');construction=trial.state.initialDeck;}catch(error){errors.push(error.message);}const accepted=report.accepted&&!errors.length;const lines=[...errors,...report.missing.map(r=>`MISSING: ${r.quantity} ${r.name}`),...report.partial.map(r=>`PARTIAL: ${r.name} — ${r.notes}`),...report.duplicates.map(r=>`DUPLICATE (preserved): ${r.quantity} ${r.name}`)];ui.deckReport={...report,accepted,errors,records:parsed.records,construction,summary:accepted?`Ready: ${construction.fixedLands} fixed lands + ${construction.selectedNonlands} selected nonlands; ${construction.reserveOrder.length} reserve candidates.`:'Deck is not ready. Resolve the issues below.',details:lines.join('\n')||'All names have registered rules. No duplicate names found.'};return ui.deckReport;}
function exportJSON(){saveDownload(`astra-session-${g.state.seed.replace(/[^a-zA-Z0-9_-]/g,'-')}.json`,g.exportSession());toast('Session exported with complete history and pending choices.');}
async function importFile(file){if(!file)return;if(file.size>50*1024*1024)throw new Error('Session exceeds the 50 MB import limit.');const document=JSON.parse(await file.text()),next=Engine.importSession(registry,document);useEngine(next);toast('Session imported and integrity checks passed.');}
function arrange(){const ids=g.state.zones[ui.zone]||[],columns=Math.max(1,Math.floor((ui.canvasWidth-22)/(ui.cardSize+15))),height=ui.cardSize*88/63+54;run({type:'LAYOUT',updates:ids.map((id,i)=>({id,x:12+(i%columns)*(ui.cardSize+15),y:14+Math.floor(i/columns)*height}))});}
async function handleClick(event){if(Date.now()<ignoreClickUntil)return;const el=event.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,id=el.dataset.id;
  if(action==='backdrop'){if(event.target===el){ui.modal=null;renderModal();}return;}
  if(action==='dialog')return openDialog(el.dataset.dialog);
  if(action==='close-dialog'){ui.modal=null;return renderModal();}
  if(action==='undo')return run({type:'UNDO'});if(action==='redo')return run({type:'REDO'});
  if(action==='mana')return run({type:'ADJUST_MANA',color:el.dataset.color,delta:Number(el.dataset.delta)});
  if(action==='clear-mana'){for(const c of COLORS)if(g.state.players[0].mana[c])run({type:'ADJUST_MANA',color:c,delta:-g.state.players[0].mana[c]});return;}
  if(action==='resource')return run({type:'ADJUST_PLAYER',player:Number(el.dataset.player),field:el.dataset.field,delta:Number(el.dataset.delta)});
  if(action==='keep')return run({type:'KEEP_HAND'});if(action==='mulligan')return run({type:'MULLIGAN'});
  if(action==='phase')return run({type:'ADVANCE_PHASE',step:el.dataset.step});if(action==='next')return run({type:'ADVANCE_PHASE',next:true});
  if(action==='next-turn')return run({type:'ADVANCE_PHASE',player:0,step:'main1',nextTurn:true});
  if(action==='opponent')return run({type:'ADVANCE_PHASE',player:Number(el.dataset.player),step:'main1'});
  if(action==='resolve')return run({type:'RESOLVE_TOP'});if(action==='resolve-all')return run({type:'RESOLVE_ALL'});if(action==='pass')return run({type:'PASS_PRIORITY'});
  if(action==='zone'){ui.zone=el.dataset.zone;ui.selected.clear();return render();}
  if(action==='select-mode'){ui.selectMode=!ui.selectMode;if(!ui.selectMode)ui.selected.clear();return render();}
  if(action==='arrange')return arrange();
  if(action==='inspect')return inspect(id);
  if(action==='card'){if(g.state.pending&&toggleChoice(id))return;if(ui.selectMode||event.shiftKey){ui.selected.has(id)?ui.selected.delete(id):ui.selected.add(id);return render();}const o=g.object(id);if(o?.zone==='battlefield'&&!g.state.pending&&g.abilities(o).filter(a=>a.mana&&a.tap).length===1)return run({type:'CARD_CLICK',id});return inspect(id);}
  if(action==='cast')return run({type:g.characteristics(id).types.includes('Land')?'PLAY_LAND':'CAST_SPELL',id});
  if(action==='ability')return run({type:'ACTIVATE_ABILITY',id,abilityId:el.dataset.ability});if(action==='plot')return run({type:'SPECIAL_ACTION',id,special:'plot'});
  if(action==='cancel')return run({type:'CANCEL'});
  if(action==='confirm-choice')return choose([...ui.choice]);if(action==='confirm-number')return choose(Number(byId('number-choice').value));
  if(action==='suggest-payment'){ui.payment=suggestPayment(g.state.pending.cost,g.state.players[g.state.pending.player||0],g.state.pending.context);return render();}
  if(action==='pay')return choose(ui.payment);
  if(action==='decline'){const p=g.state.pending;return choose(p.kind==='optional'?'NO':p.kind==='effectPayment'||p.kind==='miracleReveal'?'decline':[]);}
  if(action==='option'){const p=g.state.pending,value=choiceOptions(p)[Number(el.dataset.option)].value;if((p.max||1)>1){ui.choice=ui.choice.includes(value)?ui.choice.filter(v=>v!==value):[...ui.choice,value];return render();}return choose(value);}
  if(action==='order'){const from=Number(el.dataset.index),to=from+Number(el.dataset.direction);if(to>=0&&to<ui.choice.length)[ui.choice[from],ui.choice[to]]=[ui.choice[to],ui.choice[from]];return render();}
  if(action==='inspector-tab'){ui.inspectorTab=el.dataset.tab;return render();}
  if(action==='note'){const result=run({type:'NOTE',text:ui.noteText});if(result.ok){ui.noteText='';render();}return;}
  if(action==='start-new'){ui.seed=byId('new-seed').value.trim()||seed();const report=auditDeck();if(!report.accepted){ui.modal='deck';renderModal();return toast('The deck needs attention before starting.',true);}useEngine(Engine.create(registry,report.records,ui.seed));toast('New seeded test started.');return;}
  if(action==='start-lab'){useEngine(createLab(registry,data.pool,el.dataset.lab));toast('Prepared laboratory session started.');return;}
  if(action==='validate-deck'){auditDeck();return renderModal();}
  if(action==='restore-pool'){ui.deckText=data.deckText;ui.deckReport=null;return renderModal();}
  if(action==='export-report'){const report=auditDeck();saveDownload('missing-cards-report.json',report);renderModal();return;}
  if(action==='export-json')return exportJSON();if(action==='export-text'){saveDownload('astra-action-log.txt',g.exportText(),'text/plain');return;}
  if(action==='verify-replay'){if(g.transaction)return toast('Finish or undo the current action before verifying replay.',true);const result=g.verifyReplay();return toast(`Replay verified: ${result.actions} actions · ${result.checksum}`);}
  if(action==='restore-previous'){const previous=await store.get('previous');if(!previous)throw new Error('No previous autosave is available in this browser.');useEngine(Engine.importSession(registry,previous.session));return toast(`Recovered autosave from ${new Date(previous.savedAt).toLocaleString()}.`);}
  if(action==='zoom'){ui.previousModal=ui.modal;ui.zoomCard=el.dataset.cardId;ui.backFace=false;ui.modal='card';return renderModal();}
  if(action==='zoom-back'){ui.modal=ui.previousModal;return renderModal();}if(action==='flip'){ui.backFace=!ui.backFace;return renderModal();}
  if(action==='attack-confirm'){const attackers=g.controlled().filter(o=>ui.selected.has(o.id)&&g.characteristics(o).types.includes('Creature')).map(o=>({id:o.id,player:ui.attacks[o.id]||1}));const result=run({type:'DECLARE_ATTACKERS',attackers});if(result.ok){ui.modal=null;ui.selected.clear();render();}return;}
  if(action==='damage-confirm'){const result=run({type:'MANUAL_DAMAGE',player:Number(byId('damage-player').value),amount:Number(byId('damage-amount').value)});if(result.ok){ui.modal=null;render();}return;}
  if(action==='debug-spawn'){const result=run({type:'DEBUG_SPAWN',cardId:byId('debug-card').value,zone:byId('debug-zone').value});if(result.ok){ui.modal=null;render();}return;}
  if(action==='debug-draw'||action==='debug-mill'){const result=run({type:action==='debug-draw'?'DEBUG_DRAW':'DEBUG_MILL',count:Number(byId('debug-count').value)});if(result.ok){ui.modal=null;render();}return;}
  if(action==='debug-shuffle')return run({type:'DEBUG_SHUFFLE'});
}
document.addEventListener('click',event=>{handleClick(event).catch(error=>toast(error.message,true));});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='deck-text')ui.deckText=el.value;if(el.id==='new-seed')ui.seed=el.value;if(el.id==='note-text')ui.noteText=el.value;if(el.id==='number-choice')ui.number=Number(el.value);if(el.id==='card-search'){ui.cardFilter=el.value;renderModal();}if(el.id==='choice-filter'){ui.choiceFilter=el.value;render();}if(el.dataset.payment){ui.payment||={normal:{},tagged:[]};ui.payment.normal[el.dataset.payment]=Number(el.value);}if(el.dataset.tagged){ui.payment||={normal:{},tagged:[]};const found=ui.payment.tagged.find(t=>t.id===el.dataset.tagged);if(found)found.amount=Number(el.value);else ui.payment.tagged.push({id:el.dataset.tagged,amount:Number(el.value)});}});
document.addEventListener('change',event=>{const el=event.target;try{if(el.dataset.setting)run({type:'SET_SETTING',key:el.dataset.setting,value:el.checked});if(el.dataset.policy)run({type:'SET_OPTIONAL',key:el.dataset.policy,value:el.value});if(el.id==='reserve-access')run({type:'RESERVE_ACCESS',enabled:el.checked});if(el.id==='card-type'){ui.cardType=el.value;renderModal();}if(el.id==='show-derived'){ui.showDerived=el.checked;renderModal();}if(el.id==='card-size'){ui.cardSize=Number(el.value);render();}if(el.dataset.playerField){const player=Number(el.dataset.player),field=el.dataset.playerField;run({type:'ADJUST_PLAYER',player,field,delta:Number(el.value)-g.state.players[player][field]});}if(el.dataset.attacker){el.checked?ui.selected.add(el.dataset.attacker):ui.selected.delete(el.dataset.attacker);}if(el.dataset.destination)ui.attacks[el.dataset.destination]=Number(el.value);if(el.id==='session-file')importFile(el.files[0]).catch(error=>toast(error.message,true));}catch(error){toast(error.message,true);}});
document.addEventListener('error',event=>{if(event.target instanceof HTMLImageElement){event.target.parentElement.classList.add('image-failed');event.target.alt+=' (local image missing)';}},true);
document.addEventListener('contextmenu',event=>{const card=event.target.closest('[data-card]');if(card){event.preventDefault();inspect(card.dataset.card);}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&ui.modal){ui.modal=null;renderModal();return;}if(event.key==='Tab'&&ui.modal){const items=[...overlay.querySelectorAll('button:not(:disabled),input:not(:disabled),select,textarea,[tabindex="0"]')].filter(el=>el.offsetParent!==null),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();exportJSON();return;}if(/INPUT|TEXTAREA|SELECT/.test(event.target.tagName))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();run({type:event.shiftKey?'REDO':'UNDO'});}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='y'){event.preventDefault();run({type:'REDO'});}});

// Pointer movement is presentation-only until release. Cross-zone drops use
// the same validated casting / land-play actions as the inspector.
document.addEventListener('pointerdown',event=>{if(event.button!==0||ui.modal||g.state.pending)return;const card=event.target.closest('[data-card]'),canvas=byId('canvas');if(card&&event.target.closest('.card-face')){const object=g.object(card.dataset.card);if(!object||!['battlefield','graveyard','hand'].includes(object.zone))return;const ids=ui.selected.has(object.id)?[...ui.selected].filter(id=>g.object(id)?.zone===object.zone):[object.id];const base=canvas.getBoundingClientRect();drag={kind:'cards',pointer:event.pointerId,x:event.clientX,y:event.clientY,zone:object.zone,id:object.id,active:false,base,items:ids.map(id=>{const el=[...document.querySelectorAll('.canvas [data-card],.hand [data-card]')].find(el=>el.dataset.card===id);if(!el)return null;const r=el.getBoundingClientRect();return{id,el,x:r.left-base.left+canvas.scrollLeft,y:r.top-base.top+canvas.scrollTop};}).filter(Boolean)};drag.timer=setTimeout(()=>{if(drag)drag.active=true;},260);}else if(ui.selectMode&&canvas?.contains(event.target)&&!card){event.preventDefault();const base=canvas.getBoundingClientRect();drag={kind:'box',pointer:event.pointerId,x:event.clientX,y:event.clientY,base,active:true,original:event.shiftKey?new Set(ui.selected):new Set()};const marquee=document.createElement('div');marquee.className='marquee';marquee.id='marquee';canvas.append(marquee);}});
document.addEventListener('pointermove',event=>{if(!drag||drag.pointer!==event.pointerId)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(Math.hypot(dx,dy)>7)drag.active=true;if(!drag.active)return;event.preventDefault();if(drag.kind==='cards'){for(const item of drag.items){item.el.classList.add('dragging');item.el.style.transform=`translate(${dx}px,${dy}px)`;}const c=byId('canvas').getBoundingClientRect();byId('canvas').classList.toggle('drag-over',ui.zone==='battlefield'&&event.clientX>=c.left&&event.clientX<=c.right&&event.clientY>=c.top&&event.clientY<=c.bottom);}else{const canvas=byId('canvas'),left=Math.min(event.clientX,drag.x),right=Math.max(event.clientX,drag.x),top=Math.min(event.clientY,drag.y),bottom=Math.max(event.clientY,drag.y);const box=byId('marquee');Object.assign(box.style,{left:`${left-drag.base.left+canvas.scrollLeft}px`,top:`${top-drag.base.top+canvas.scrollTop}px`,width:`${right-left}px`,height:`${bottom-top}px`});ui.selected=new Set(drag.original);for(const el of canvas.querySelectorAll('[data-card]')){const r=el.getBoundingClientRect();if(r.left<right&&r.right>left&&r.top<bottom&&r.bottom>top)ui.selected.add(el.dataset.card);el.classList.toggle('is-selected',ui.selected.has(el.dataset.card));}}},{passive:false});
function finishDrag(event,cancel=false){if(!drag||drag.pointer!==event.pointerId)return;const d=drag;drag=null;clearTimeout(d.timer);byId('marquee')?.remove();byId('canvas')?.classList.remove('drag-over');if(d.kind==='cards')for(const i of d.items){i.el.classList.remove('dragging');i.el.style.transform='';}if(!d.active||cancel)return;ignoreClickUntil=Date.now()+250;if(d.kind==='box'){render();return;}const canvas=byId('canvas'),r=canvas.getBoundingClientRect(),inside=event.clientX>=r.left&&event.clientX<=r.right&&event.clientY>=r.top&&event.clientY<=r.bottom;if(!inside){render();return;}const dx=event.clientX-d.x,dy=event.clientY-d.y;if(d.zone===ui.zone&&['battlefield','graveyard'].includes(d.zone)){run({type:'LAYOUT',updates:d.items.map(i=>({id:i.id,x:Math.max(0,Math.min(10000,i.x+dx)),y:Math.max(0,Math.min(10000,i.y+dy))}))});}else if(ui.zone==='battlefield'){run({type:'DROP_CARD',id:d.id,zone:'battlefield'});}else{toast('Cross-zone movement requires a legal spell, ability or effect.',true);render();}}
document.addEventListener('pointerup',event=>finishDrag(event));document.addEventListener('pointercancel',event=>finishDrag(event,true));
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!drag)render();},120);});
window.addEventListener('pagehide',()=>{saveNow().catch(()=>{});});
window.astra={get engine(){return g;},registry,ui,run,flushSave:saveNow,get storage(){return store;}};
async function boot(){await store.open();saveStatus.text=store.mode==='memory'?'Autosave unavailable — export to preserve your session.':'Browser storage ready.';saveStatus.error=store.mode==='memory';let recovered=null;try{const latest=await store.get();if(latest){recovered=Engine.importSession(registry,latest.session);saveStatus.text=`Restored autosave from ${new Date(latest.savedAt).toLocaleString()}`;}}catch(error){try{const previous=await store.get('previous');if(previous){recovered=Engine.importSession(registry,previous.session);saveStatus.text='Recovered the previous autosave; newest record failed integrity checks.';}else throw error;}catch{saveStatus.text=`Could not recover autosave: ${error.message}`;saveStatus.error=true;}}useEngine(recovered||Engine.create(registry,data.pool,ui.seed),false);}
boot().catch(error=>{root.innerHTML=`<div class="fatal"><h1>Unable to start Astra</h1><p>${h(error.message)}</p><p>Keep this folder together with its local assets. Run the included verification command to inspect the installation.</p></div>`;console.error(error);});
