import { h, button, logo, manaText, empty } from './components.js';
import { LABS } from './labs.js';
export function dialogHTML({g,ui,registry,saveStatus}) {
  if(!ui.modal)return '';const s=g.state;let title='',subtitle='',body='',footer='',narrow=false;
  if(ui.modal==='new') {
    title='A new line of play';subtitle='A reproducible opening hand. A fresh experiment.';narrow=true;
    body=`<p>The candidate harness keeps every main-pool land, selects enough nonlands for an active 99, and isolates the remaining candidates beneath it.</p><div class="deck-summary"><div class="metric"><strong>34</strong><small>Fixed lands in supplied pool</small></div><div class="metric"><strong>65</strong><small>Selected nonlands</small></div></div><label class="stacked">Random seed<input id="new-seed" value="${h(ui.seed)}" maxlength="200" autocomplete="off"></label><p class="muted" style="margin-top:12px">The same deck and seed reproduce the same initial active and reserve order. Current deck editor contents are used; unsupported names are rejected.</p><div class="callout">Starting a new test replaces the table. Export the current session to keep an independent copy.</div>`;
    footer=button('Export current session','export-json')+button('Start seeded test','start-new','','primary');
  } else if(ui.modal==='labs') {
    title='The laboratory';subtitle='Five prepared tables for exploring the engine. No manual overrides required.';
    body=`<p>These are explicitly labelled scenarios, not randomized opening hands. Each begins at your first main phase with prepared permanents, cards and mana.</p><div class="lab-grid">${LABS.map((l,i)=>`<button class="lab-tile" data-action="start-lab" data-lab="${h(l.id)}"><span class="lab-number">EXPERIMENT 0${i+1}</span><strong>${h(l.name)}</strong><small>${h(l.tag)}</small><p>${h(l.description)}</p></button>`).join('')}</div>`;
  } else if(ui.modal==='cards') {
    title='The local card registry';subtitle='160 candidate cards · canonical rules text · local images';
    const query=ui.cardFilter.toLowerCase(),type=ui.cardType;
    const cards=registry.list().filter(c=>(ui.showDerived||c.candidate)&&(!type||c.types.includes(type))&&`${c.name} ${c.oracleText} ${c.typeLine}`.toLowerCase().includes(query)).sort((a,b)=>a.name.localeCompare(b.name));
    body=`<div class="row wrap"><input class="grow" id="card-search" aria-label="Search card registry" placeholder="Search name, type or rules text…" value="${h(ui.cardFilter)}"><select id="card-type" aria-label="Filter card type"><option value="">All types</option>${['Artifact','Creature','Enchantment','Instant','Sorcery','Land','Planeswalker'].map(t=>`<option ${type===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="spread" style="margin-top:14px"><span class="muted">${cards.length} matching definitions</span><label class="muted"><input type="checkbox" id="show-derived" ${ui.showDerived?'checked':''}> Include tokens and derived faces</label></div><div class="library-grid">${cards.map(c=>`<article class="registry-card"><button data-action="zoom" data-card-id="${h(c.id)}" aria-label="Read ${h(c.name)}"><img src="${h(c.image)}" alt="${h(c.name)}" loading="lazy"><div class="registry-caption">${h(c.name)}<small>${h(c.typeLine)} · MV ${c.manaValue}</small><small>${registry.module(c.id).status==='full'?'Registered rules':'Derived / scoped definition'}</small></div></button></article>`).join('')||empty('No matching cards','Try a broader search.')}</div>`;
  } else if(ui.modal==='card') {
    const c=registry.get(ui.zoomCard);title=c.name;subtitle=c.typeLine;
    body=`<div class="guide-grid"><div><img src="${h(ui.backFace&&c.backImage?c.backImage:c.image)}" alt="${h(c.name)}" style="width:100%;border-radius:13px">${c.backImage?button('Show other face','flip','','ability'):''}</div><div><div class="row wrap">${manaText(c.manaCost)}<span class="pill">Mana value ${c.manaValue}</span></div><div class="oracle">${h(c.oracleText)}</div><p class="muted">Oracle ID ${h(c.id)}<br>Printing ${h(c.set||'')} ${h(c.collectorNumber||'')}</p><h3>Canonical rulings</h3>${(c.rulings||[]).map(r=>`<p class="muted">${h(r.comment)}</p>`).join('')||'<p class="muted">No additional rulings in this local snapshot.</p>'}</div></div>`;
    footer=button('Back','zoom-back');
  } else if(ui.modal==='deck') {
    title='Your candidate pool';subtitle='Copies are physical objects. Duplicates are preserved and reported.';
    body=`<div class="deck-summary"><div class="metric"><strong>119</strong><small>Supplied main-pool copies</small></div><div class="metric"><strong>34</strong><small>Supplied fixed lands</small></div><div class="metric"><strong>20</strong><small>Supplied reserve cards</small></div><div class="metric"><strong>41</strong><small>Outside-the-game cards</small></div></div><label class="stacked">Deck list<textarea id="deck-text" rows="14" spellcheck="false" aria-label="Deck list">${h(ui.deckText)}</textarea></label><p class="muted">Use quantities and names. Section headings: // Main, // Commander, // Outside the Game. Exactly one commander is required by this harness. Editing the list does not change an in-progress game.</p>${ui.deckReport?`<div class="callout ${ui.deckReport.accepted?'success':'warning'}">${h(ui.deckReport.summary)}</div><pre style="white-space:pre-wrap;font-size:11px">${h(ui.deckReport.details)}</pre>`:''}<div class="callout">Scroll Rack appears twice in the supplied source list. Both copies remain in the candidate pool; this is a testing harness, not a deck-legality validator.</div>`;
    footer=button('Restore supplied pool','restore-pool')+button('Export missing-card report','export-report')+button('Validate deck','validate-deck','','primary');
  } else if(ui.modal==='save') {
    title='Keep your experiment';subtitle='Full history, pending choices, seed, deck order and undo state.';narrow=true;
    body=`<div class="callout ${saveStatus.error?'error':'success'}">${h(saveStatus.text)}</div><div class="stacked">${button('Export session.json','export-json','','primary')}${button('Export readable action log','export-text')}${button('Verify deterministic replay','verify-replay')}</div><hr class="divider"><label class="stacked">Import a saved session<input type="file" id="session-file" accept=".json,application/json"></label><p class="muted" style="margin-top:10px">The checksum, zone consistency and history are checked before your current game is replaced.</p>${button('Recover previous autosave','restore-previous')}<div class="callout">Browser storage belongs to this browser and file/origin. Moving to another computer requires an exported session. Export before clearing browser data.</div>`;
  } else if(ui.modal==='settings') {
    title='Table settings';subtitle='Rules stay explicit. Every manual adjustment is logged.';
    const setting=(key,label,description)=>`<div class="setting-row"><input type="checkbox" id="setting-${key}" data-setting="${key}" ${s.settings[key]?'checked':''}><label for="setting-${key}"><strong>${label}</strong><small>${description}</small></label></div>`;
    body=`${setting('holdPriority','Hold priority','Leave your spells and abilities on the stack so you can respond to them.')}${setting('orderTriggers','Choose simultaneous trigger order','Arrange your triggers in the order they should resolve. Disabling uses deterministic event order.')}${setting('firstMulliganFree','First multiplayer mulligan is free','This applies before an opening hand is kept. Later mulligans use London bottoming.')}<div class="setting-row"><input type="checkbox" id="reserve-access" ${s.reserveAccess?'checked':''}><label for="reserve-access"><strong>Explicitly allow reserve access</strong><small>Harness override: searches may see reserve candidates, and draws reach them after active cards. This changes the experiment and is logged.</small></label></div><div class="setting-row"><label for="card-size"><strong>Card size · ${ui.cardSize}px</strong><small>Applies to the battlefield and hand.</small></label><input id="card-size" type="range" min="90" max="155" step="5" value="${ui.cardSize}"></div><h3 style="margin-top:22px">Abstract opponent state</h3><p class="muted">These counts support sacrifice and hand-size effects. Combat damage is explicitly user-assisted; there is no multiplayer AI.</p>${s.players.slice(1).map(p=>`<div class="setting-row"><strong class="grow">${h(p.name)}</strong><label>Creatures <input type="number" min="0" max="1000" data-player-field="abstractCreatures" data-player="${p.id}" value="${p.abstractCreatures}"></label><label>Hand <input type="number" min="0" max="1000" data-player-field="abstractHand" data-player="${p.id}" value="${p.abstractHand}"></label></div>`).join('')}<hr class="divider">${setting('debug','Enable developer overrides','Disabled by default. Force moves, draws and state changes are marked DEBUG_OVERRIDE and are not rules-valid gameplay.')}${s.settings.debug?`<div class="callout warning">Developer actions below alter the test state. They are never a substitute for an unsupported card implementation.</div><div class="row wrap"><select id="debug-card" aria-label="Card to spawn">${registry.list().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${h(c.id)}">${h(c.name)}</option>`).join('')}</select><select id="debug-zone"><option value="battlefield">Battlefield</option><option value="hand">Hand</option><option value="graveyard">Graveyard</option><option value="libraryActive">Library bottom</option></select>${button('Spawn','debug-spawn','','danger')}</div><div class="row wrap" style="margin-top:12px"><label>Count <input id="debug-count" type="number" value="1" min="0" max="1000"></label>${button('Draw N','debug-draw','','danger')}${button('Mill N','debug-mill','','danger')}${button('Shuffle library','debug-shuffle','','danger')}</div>`:''}`;
  } else if(ui.modal==='combat') {
    title='Declare attackers';subtitle='Choose creatures and destinations. Tapping, vigilance and haste follow the rules.';
    const creatures=g.controlled().filter(o=>g.characteristics(o).types.includes('Creature')&&!o.tapped&&!g.isSick(o)&&!o.flags.attacking);
    body=`${creatures.length?creatures.map(o=>`<div class="setting-row"><input type="checkbox" data-attacker="${h(o.id)}" ${ui.selected.has(o.id)?'checked':''}><label class="grow">${h(g.definition(o).name)} <small>${g.characteristics(o).power}/${g.characteristics(o).toughness}</small></label><select data-destination="${h(o.id)}" aria-label="Attack destination for ${h(g.definition(o).name)}">${s.players.slice(1).filter(p=>!p.lost).map(p=>`<option value="${p.id}" ${(ui.attacks[o.id]||1)===p.id?'selected':''}>${h(p.name)}</option>`).join('')}</select></div>`).join(''):'<p>No untapped creatures can attack right now.</p>'}<p class="muted">Declaring attackers is one simultaneous action. Damage and blockers are user-assisted in this goldfish scope.</p>`;
    footer=button('Declare selected attackers','attack-confirm','','primary');
  } else if(ui.modal==='damage') {
    title='Combat damage assistance';subtitle='This manual adjustment is clearly marked in the session log.';narrow=true;
    body=`<div class="stacked"><label>Recipient<select id="damage-player" style="display:block;width:100%">${s.players.slice(1).filter(p=>!p.lost).map(p=>`<option value="${p.id}">${h(p.name)}</option>`).join('')}</select></label><label>Damage <input id="damage-amount" type="number" min="0" max="1000000" value="0"></label></div><p class="muted" style="margin-top:14px">Only available in the attack, damage and end-combat steps. This does not model blockers, prevention by unimplemented opponents, or complete damage assignment.</p>`;
    footer=button('Apply manual combat damage','damage-confirm','','primary');
  } else if(ui.modal==='guide') {
    title='A rules-aware place to experiment';subtitle='Play the line yourself. Let the engine keep the bookkeeping honest.';
    body=`<div class="guide-grid"><section><h3>Start a test</h3><p>New test uses your deck editor, fixes the lands and commander, then selects and shuffles the active 99 by seed. The 20 spare candidates in the supplied pool stay isolated. Keep your opening hand, then click Main 1 to process untap, upkeep and draw in order. Advancement pauses for decisions and triggers.</p><h3>Cast and pay</h3><p>Click a card’s name to inspect it, then choose Cast or Play. Dragging a hand card onto the battlefield requests the same legal action; it is not a force move. Mana is never auto-tapped. Activate a mana ability or adjust the pool explicitly, then allocate payment. Multiple play permissions, X, sacrifice costs and targets each receive their own selector.</p><h3>Use the stack</h3><p>Hold priority is on by default. Resolve top, resolve all, or respond with an instant or ability. Resolve all pauses for choices. Trigger ordering is shown in <b>resolution order</b>: the first row resolves first. Triggers produced during a resolving effect wait for that effect to finish.</p></section><section><h3>Move around the table</h3><p>Click a battlefield image for its single tap-mana ability. Cards with multiple choices are inspected instead. Tapped cards need a legal untap effect. Drag or long-press a card to reposition it in the battlefield or graveyard. Select mode, Shift-click, and marquee selection support moving groups without changing zones.</p><h3>Save, undo, reproduce</h3><p>Undo reverses an entire action including its choices; an in-progress action can also be rolled back. Redo restores exact random results. Browser autosave includes pending choices, and Save session exports a portable file with the complete history. Notes travel with the session. <kbd>Ctrl Z</kbd> undo; <kbd>Ctrl Shift Z</kbd> redo; <kbd>Ctrl S</kbd> export.</p><h3>Scope, not a multiplayer judge</h3><p>The supplied card pool has registered capabilities; the three opponents are abstract. Their life, hand and creature counts can be adjusted. Blocking and combat damage assignment are user-assisted. Developer overrides are off by default and conspicuously logged. Unsupported deck names are rejected rather than silently treated as vanilla cards.</p></section></div><div class="callout">Runtime is offline. All 175 card, token and derived-face images are included locally. Metadata import belongs to the developer workflow, not to a play session.</div>`;
  }
  return `<div class="modal-backdrop" data-action="backdrop"><section class="modal ${narrow?'narrow':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-header"><div><h2 id="modal-title">${h(title)}</h2><p>${h(subtitle)}</p></div>${button('×','close-dialog','aria-label="Close dialog"','quiet')}</div><div class="modal-body" data-scroll="modal">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}</section></div>`;
}
