import { COLORS, STEPS, suggestPayment, manaCostText } from '../core/index.js';
import { h, asset, logo, button, cardHTML, manaPoolHTML, manaText, symbol, empty, STEP_NAMES, ZONE_NAMES } from './components.js';
export function headerHTML({g,ui}) {
  const s=g.state;
  return `<header class="app-header"><div class="brand">${logo}<div><div class="wordmark">ASTRA</div><div class="tagline">THE GOLDFISH LAB</div></div></div><nav class="header-nav" aria-label="Application">${button('New test','dialog', 'data-dialog="new"','quiet')}${button('Laboratory','dialog','data-dialog="labs"','quiet')}${button('Cards <span class="muted">160</span>','dialog','data-dialog="cards"','quiet')}${button('Deck pool','dialog','data-dialog="deck"','quiet')}${button('Guide','dialog','data-dialog="guide"','quiet')}</nav><div class="header-actions"><span class="offline-label">Offline · local rules</span>${button('↶','undo',`aria-label="Undo" title="Undo (Ctrl+Z)" ${!g.cursor&&!g.transaction?'disabled':''}`)}${button('↷','redo',`aria-label="Redo" title="Redo (Ctrl+Shift+Z)" ${g.cursor>=g.history.length||g.transaction?'disabled':''}`)}${button('Save session','dialog','data-dialog="save"')}${button('⚙','dialog','data-dialog="settings" aria-label="Settings"')}</div></header><section class="phase-bar"><div class="turn-label"><strong>Turn ${s.turnNumber}</strong><small>${s.activePlayer===0?'Your turn':`Opponent ${s.activePlayer}`}</small></div><nav class="phase-steps" aria-label="Turn steps">${STEPS.map(step=>button(h(STEP_NAMES[step]),'phase',`data-step="${step}" ${!s.started?'disabled':''}`,s.step===step?'active':'quiet')).join('')}</nav><div class="row">${button('Next step →','next',!s.started?'disabled':'')}${button('Your next turn','next-turn',!s.started?'disabled':'')}${['attackers','damage','endCombat'].includes(s.step)?button('Assign damage','dialog','data-dialog="damage"'):''}</div></section>`;
}
export function sidebarHTML({g}) {
  const s=g.state,p=s.players[0],top=g.top(),visible=g.hasStatic('lookTop');
  const adjust=(player,field,value,label)=>`<div class="resource-row"><span class="grow">${h(label)}</span>${button('−','resource',`data-player="${player}" data-field="${field}" data-delta="-1" aria-label="Decrease ${h(label)} for player ${player}"`)}<span class="value">${value}</span>${button('+','resource',`data-player="${player}" data-field="${field}" data-delta="1" aria-label="Increase ${h(label)} for player ${player}"`)}</div>`;
  return `<aside class="resources" aria-label="Resources"><section class="resource-section library-section ${visible?'top-visible':''}"><div class="eyebrow">Your library</div>${visible&&top?cardHTML(g,top.id,{small:true}):`<div class="deck-back">${logo}<strong>${s.zones.libraryActive.length}</strong></div>`}<div class="spread library-stat"><span>Active cards</span><b>${s.zones.libraryActive.length}</b></div><div class="spread library-stat"><span>Reserve ${s.reserveAccess?'enabled':'isolated'}</span><b>${s.zones.libraryReserve.length}</b></div><p class="muted">${visible?'Top card is visible by a rules permission.':'Top card concealed.'}</p>${!s.started?`<div class="stacked">${button('Keep hand','keep','','primary')}${button(`Mulligan${s.mulligans?` (${s.mulligans})`:''}`,'mulligan')}</div>`:''}</section><section class="resource-section command-section"><div class="eyebrow">Command zone</div>${s.zones.command.length?s.zones.command.map(id=>cardHTML(g,id,{small:true})).join(''):'<div class="empty-command muted">No commander in this zone.</div>'}</section><section class="resource-section"><div class="spread"><div class="eyebrow">Mana pool</div>${button('Clear','clear-mana','title="Manually clear unrestricted mana"','quiet')}</div>${manaPoolHTML(p)}</section><section class="resource-section"><div class="eyebrow">Your resources</div><div class="life-row">${button('−','resource','data-player="0" data-field="life" data-delta="-1" aria-label="Lose 1 life"')}<strong>${p.life}</strong>${button('+','resource','data-player="0" data-field="life" data-delta="1" aria-label="Gain 1 life"')}</div>${adjust(0,'energy',p.energy,'Energy')}${adjust(0,'poison',p.poison,'Poison')}${s.status!=='playing'?`<div class="callout warning">${h(s.status)}</div>`:''}</section><section class="resource-section opponents-section"><div class="eyebrow">Abstract opponents</div>${s.players.slice(1).map(o=>`<div class="opponent"><div class="spread"><span>${h(o.name)}</span>${o.lost?'<span class="pill">Out</span>':''}</div>${adjust(o.id,'life',o.life,'Life')}${button('→ Main 1','opponent',`data-player="${o.id}" ${!s.started||o.lost?'disabled':''} title="Advance through this opponent’s untap, upkeep and draw"`)}</div>`).join('')}</section></aside>`;
}
export function tableHTML(ctx) {
  const {g,ui}=ctx,s=g.state,p=s.pending,legal=p?.candidates||p?.ids||[],ids=ui.zone==='workspace'?(s.lookWorkspace?.ids||[]):s.zones[ui.zone]||[];
  const width=ui.cardSize,columns=Math.max(1,Math.floor((ui.canvasWidth-22)/(width+15))),height=width*88/63+54;
  const positions=ids.map((id,i)=>({id,x:g.object(id)?.location?.x??12+(i%columns)*(width+15),y:g.object(id)?.location?.y??14+Math.floor(i/columns)*height}));
  const canvasHeight=Math.max(350,...positions.map(p=>p.y+height+8));
  const cards=positions.map(pos=>`<div class="card-slot" style="position:absolute;left:${pos.x}px;top:${pos.y}px">${cardHTML(g,pos.id,{selected:ui.selected,legal})}</div>`).join('');
  return `<main class="table" id="table"><div class="zone-nav" aria-label="Visible zone">${['battlefield','graveyard','exile','workspace','outside'].map(z=>button(`${h(ZONE_NAMES[z])}<span class="count">${z==='workspace'?s.lookWorkspace?.ids.length||0:s.zones[z].length}</span>`,'zone',`data-zone="${z}"`,ui.zone===z?'active':'quiet')).join('')}<span class="grow"></span>${button('Select','select-mode',`aria-pressed="${ui.selectMode}"`,ui.selectMode?'active':'')}${button('Arrange','arrange',`title="Arrange cards in this zone" ${!['battlefield','graveyard'].includes(ui.zone)?'disabled':''}`)}</div><div class="table-meta"><span>Land plays <b>${s.landPlaysUsed} / ${g.landAllowance()}</b> · Putting a land into play is not a land play.</span><span>Library ${s.zones.libraryActive.length} · Reserve ${s.zones.libraryReserve.length}</span></div>${s.settings.debug?'<div class="callout warning">Developer overrides enabled. Overrides are marked in your action history.</div>':''}${s.initialDeck.scenario?`<div class="table-meta"><span>${h(s.initialDeck.scenario)} · prepared laboratory scenario</span></div>`:''}${!s.started?`<div class="callout spread"><span>Choose your opening hand. First multiplayer mulligan is ${s.settings.firstMulliganFree?'free':'not free'}.</span><div class="row">${button('Mulligan','mulligan')}${button('Keep hand','keep','','primary')}</div></div>`:''}${p?decisionHTML(ctx):''}${s.step==='attackers'&&s.activePlayer===0&&!p?`<div class="callout spread"><span>Select creatures to attack.</span>${button('Declare attackers','dialog','data-dialog="combat"')}</div>`:''}<div class="canvas ${ui.selectMode?'select-mode':''}" id="canvas" data-layout-zone="${h(ui.zone)}" data-scroll="canvas" style="height:${Math.min(canvasHeight,Math.max(410,innerHeight*.56))}px"><div style="position:relative;min-width:100%;height:${canvasHeight}px">${cards||empty(ui.zone==='battlefield'?'Your next line starts here':`No cards in ${ZONE_NAMES[ui.zone].toLowerCase()}`,ui.zone==='battlefield'?'Play a land, build an engine, and see where it leads. Cross-zone movement always follows the rules.':'Cards arrive here through game actions and resolving effects.')}</div></div><div class="spread hand-header"><span>Your hand <span class="muted">· ${s.zones.hand.length} cards</span></span><small>Inspect to cast / play · drag to battlefield</small></div><div class="hand" data-scroll="hand">${s.zones.hand.map(id=>cardHTML(g,id,{selected:ui.selected,legal})).join('')||'<p class="muted">Your hand is empty.</p>'}</div></main>`;
}
export function choiceOptions(p) {
  if(p.options) return p.options.map(o=>typeof o==='object'?o:{value:o,label:String(o)});
  if(p.kind==='commander')return[{value:'command',label:'Move to command zone'},{value:'stay',label:'Leave in current zone'}];
  if(p.kind==='miracleReveal')return[{value:'reveal',label:'Reveal for miracle'},{value:'decline',label:'Do not reveal'}];
  return [];
}
export function decisionHTML({g,ui}) {
  const p=g.state.pending;if(!p)return '';const ids=p.candidates||p.ids||[],options=choiceOptions(p),ordered=!!p.ordered;
  let content='',footer='';
  const remember=(p.kind==='optional'||p.policyKey)?'<label class="muted"><input type="checkbox" id="remember-choice"> Remember this preference</label>':'';
  if(['payment','effectPayment'].includes(p.kind)) {
    const player=g.state.players[p.player||0],suggested=suggestPayment(p.cost,player,p.context),pay=ui.payment||{normal:{},tagged:[]};
    content=`<p class="muted">${h(p.description||'Pay from your pool. You may activate mana abilities while this payment is waiting.')}</p><div class="payment-grid">${COLORS.map(c=>`<label>${symbol(c)}<input type="number" min="0" max="${player.mana[c]}" data-payment="${c}" id="pay-${c}" value="${pay.normal?.[c]||0}" aria-label="Spend ${c} mana"><small>of ${player.mana[c]}</small></label>`).join('')}</div>${player.restrictedMana.map(t=>`<label class="resource-row"><span>${symbol(t.color)} ${h(t.restriction)} (${t.amount})</span><input type="number" min="0" max="${t.amount}" data-tagged="${h(t.id)}" value="${pay.tagged?.find(v=>v.id===t.id)?.amount||0}" aria-label="Spend restricted mana"></label>`).join('')}${p.cost.life?`<p>Additional life payment: <b>${p.cost.life}</b></p>`:''}<div class="row wrap">${button('Use suggested allocation','suggest-payment',!suggested?'disabled':'')}<small>${suggested?'Suggestion uses existing mana only.':'Not enough eligible mana in the pool yet.'}</small></div><details><summary class="muted">Available mana abilities</summary><div class="payment-sources">${g.controlled().flatMap(o=>g.abilities(o).filter(a=>a.mana).map(a=>button(`${h(g.definition(o).name)} · ${h(a.label||a.id)}`,'ability',`data-id="${h(o.id)}" data-ability="${h(a.id)}" ${a.tap&&(o.tapped||g.isSick(o))?'disabled':''}`))).join('')}</div></details>`;
    footer=button(`Pay ${h(manaCostText(p.cost))}`,'pay','','primary')+(p.kind==='effectPayment'?button('Decline','decline'):button('Cancel casting / activation','cancel'));
  } else if(p.type==='number') {
    content=`<label>${h(p.label)} <input id="number-choice" type="number" min="${p.min??0}" max="${p.max??10000}" value="${ui.number}"></label>`;footer=button('Confirm number','confirm-number','','primary')+button('Cancel action','cancel');
  } else if(ordered) {
    content=`<p class="muted">${h(p.description||'The first item is the top card. Use the arrows to change the order.')}</p><div class="ordered-list" data-scroll="ordered">${ui.choice.map((id,i)=>`<div class="choice-row"><span class="ordinal">${i+1}</span><span>${h(options.find(o=>o.value===id)?.label||g.definition(g.object(id)).name)}</span>${button('↑','order',`data-index="${i}" data-direction="-1" ${i===0?'disabled':''} aria-label="Move item ${i+1} earlier"`)}${button('↓','order',`data-index="${i}" data-direction="1" ${i===ui.choice.length-1?'disabled':''} aria-label="Move item ${i+1} later"`)}</div>`).join('')}</div>`;
    footer=button(p.kind==='triggerOrder'?'Confirm resolution order':'Confirm top-first order','confirm-choice','','primary');
  } else if(options.length && !ids.length && p.type!=='select') {
    content=`<div class="option-buttons">${options.map((o,i)=>button(h(o.label),'option',`data-option="${i}"`,ui.choice.includes(o.value)?'active':'')).join('')}</div>${remember}`;
    if((p.max||1)>1)footer=button(`Confirm ${ui.choice.length} choices`,'confirm-choice','','primary');
  } else {
    const filtered=ids.filter(id=>{const o=g.object(id);return o&&`${g.definition(o).name} ${g.characteristics(o).typeLine}`.toLowerCase().includes(ui.choiceFilter.toLowerCase());});
    content=`<div class="spread"><span class="muted">${h(p.cost?'This selection is a COST, paid before the ability goes on the stack.':'Only legal cards are shown.')} Choose ${p.min===p.max?p.min:`${p.min||0}–${p.max||1}`}.</span><span class="selected-count">${ui.choice.length} selected</span></div>${ids.length>8?`<input id="choice-filter" class="choice-search" placeholder="Filter legal cards by name or type…" value="${h(ui.choiceFilter)}" aria-label="Filter legal cards">`:''}<div class="decision-gallery" data-scroll="choices">${filtered.map(id=>cardHTML(g,id,{selected:new Set(ui.choice),legal:ids})).join('')||'<p class="muted">No matching legal cards.</p>'}</div>`;
    footer=button(`Confirm ${ui.choice.length?`(${ui.choice.length})`:p.min===0?' / choose none':''}`,'confirm-choice',ui.choice.length<(p.min||0)||ui.choice.length>(p.max||1)?'disabled':'','primary');
  }
  if(!['payment','effectPayment'].includes(p.kind)&&p.optional)footer+=button('Decline / skip','decline');
  else if(p.kind==='draft'&&p.type!=='number')footer+=button('Cancel action','cancel');
  return `<section class="decision" aria-label="Pending decision"><div class="decision-header"><div class="eyebrow">Decision required · ${h(p.kind)}</div><h3 id="decision-title">${h(p.label)}</h3></div><div class="decision-body">${content}</div>${footer?`<div class="decision-footer">${footer}</div>`:''}</section>`;
}
export function inspectorHTML({g,ui}) {
  const s=g.state,stack=[...s.stack].reverse(),o=g.object(ui.inspected),d=o?g.definition(o):null,c=o?g.characteristics(o):null,m=o?g.module(o):{};
  let content='';
  if(ui.inspectorTab==='log')content=`<div class="spread"><h3>Action history</h3>${button('Export text','export-text')}</div><p class="muted">${g.cursor} committed actions. Choices and costs are part of their parent action.</p>${[...(g.transaction?[{index:'…',label:g.transaction.label,events:g.transaction.events}]:[]),...g.history.slice(0,g.cursor).reverse().slice(0,100)].map(e=>`<details class="log-entry"><summary>#${e.index} · ${h(e.label)} <span class="muted">${e.events.length} events</span></summary><pre>${h(JSON.stringify(e.events,null,2))}</pre></details>`).join('')||empty('No actions yet','Your legal actions, choices and random results will appear here.')}`;
  else if(ui.inspectorTab==='notes')content=`<h3>Testing notes</h3><textarea id="note-text" rows="4" placeholder="Record a line, an observation, or a question…">${h(ui.noteText)}</textarea>${button('Add note','note','','primary')}<div>${[...s.notes].reverse().map(n=>`<div class="note"><small>Turn ${n.turn} · ${h(STEP_NAMES[n.step]||n.step)}</small>${h(n.text)}</div>`).join('')}</div>`;
  else if(!o)content=empty('The card inspector','Use a card’s name to inspect its rules, live characteristics and available abilities. A short click on a battlefield image requests a mana ability; it never forces an untap.');
  else {
    const land=c.types.includes('Land'),permissions=g.castingPermissions(o,land),abilities=g.abilities(o),canCast=['hand','command','graveyard','exile','libraryActive','libraryReserve'].includes(o.zone)&&permissions.length;
    content=`${button(`<img class="inspector-image" src="${h(asset(d.image))}" alt="${h(d.name)}">`,'zoom',`data-card-id="${h(d.id)}"`,'quiet')}<h2 class="inspect-title">${h(d.name)}</h2><div class="row wrap">${manaText(d.manaCost)}<span class="pill">MV ${c.manaValue}</span>${o.token?'<span class="pill gold">Token copy</span>':''}</div><div class="detail-line" style="margin-top:9px">${h([...c.supertypes,...c.types].join(' '))}${c.subtypes.length?` — ${h(c.subtypes.join(' '))}`:''}</div><div class="row wrap" style="margin-top:8px">${c.types.includes('Creature')?`<span class="pill gold">${c.power} / ${c.toughness}</span>`:''}${c.keywords.filter(k=>!['Landfall','Affinity'].includes(k)).map(k=>`<span class="pill">${h(k)}</span>`).join('')}</div><div class="oracle">${h(d.oracleText)}</div><div class="detail-line">${h(ZONE_NAMES[o.zone])} · Object ${h(o.id)}:${o.oid}${o.zone==='battlefield'?` · ${o.tapped?'Tapped':'Untapped'}${g.isSick(o)?' · Summoning sickness':''}`:''}</div>${o.attachedTo?`<div class="detail-line">Attached to ${h(g.object(o.attachedTo)?g.definition(g.object(o.attachedTo)).name:'a departed object')}</div>`:''}${Object.keys(o.counters).length?`<div class="detail-line">Counters: ${h(Object.entries(o.counters).map(([k,n])=>`${n} ${k}`).join(', '))}</div>`:''}<hr class="divider">${m.status!=='full'?`<div class="callout warning">${h(m.notes||'This card has not passed the pack’s automation acceptance.')}</div>`:''}${canCast?button(land?'Play this land':'Cast this spell','cast',`data-id="${h(o.id)}"`,'ability primary'):''}${m.plot&&o.zone==='hand'?button(`Plot ${h(m.plot)}`,'plot',`data-id="${h(o.id)}"`,'ability'):''}${abilities.map(a=>button(`${h(a.label||a.id)}<small>${a.tap?'Tap · ':''}${typeof a.cost==='string'?h(a.cost)+' · ':''}${a.mana?'Mana ability · no stack':a.loyalty!=null?'Loyalty ability':'Activated ability'}</small>`,'ability',`data-id="${h(o.id)}" data-ability="${h(a.id)}"`,'ability')).join('')}${!canCast&&!abilities.length?'<p class="muted">No activated action available from this zone. Static and triggered abilities are automatic.</p>':''}${optionalHTML(g,o)}<details><summary class="muted">Canonical rulings (${d.rulings?.length||0})</summary>${(d.rulings||[]).map(r=>`<p class="muted" style="margin:10px 0">${h(r.comment)}</p>`).join('')}</details>`;
  }
  return `<aside class="inspector-pane"><section class="stack-panel"><div class="spread"><h3>Stack <span class="muted">${stack.length||''}</span></h3><span class="pill gold">${s.pending?'Decision pending':'Priority is yours'}</span></div><div class="stack-list" data-scroll="stack">${stack.map((v,i)=>`<div class="stack-item"><small>${i===0?'Resolves next':`Then ${i+1}`} · ${h(v.kind)}</small>${h(v.label)}</div>`).join('')||'<p class="muted" style="margin:12px 0">No spells or abilities waiting.</p>'}${s.resolving?`<div class="stack-item"><small>Resolving · paused for a choice</small>${h(s.resolving.object.label)}</div>`:''}</div><div class="row">${button('Resolve top','resolve',!stack.length||s.pending?'disabled':'','primary grow')}${button('All','resolve-all',!stack.length||s.pending?'disabled':'')}${button('Pass','pass',!s.started||s.pending?'disabled':'')}</div><label class="muted" style="margin-top:10px"><input type="checkbox" data-setting="holdPriority" ${s.settings.holdPriority?'checked':''}> Hold priority after my spells and abilities</label></section><nav class="inspector-tabs">${['inspect','log','notes'].map(tab=>button({inspect:'Inspector',log:'Action log',notes:'Notes'}[tab],'inspector-tab',`data-tab="${tab}"`,ui.inspectorTab===tab?'active':'')).join('')}</nav><div class="inspector-content" data-scroll="inspector">${content}</div></aside>`;
}
function optionalHTML(g,o) {
  const m=g.module(o),keys=(m.triggers||[]).filter(t=>t.optional).map(t=>({id:t.id,label:t.label||t.id}));
  if(g.definition(o).name==='Tireless Provisioner')keys.push({id:'token-kind',label:'Landfall token',provisioner:true});
  if(!keys.length)return '';
  return `<details style="margin:14px 0"><summary class="muted">Optional-effect preferences</summary>${keys.map(k=>{const key=`${o.copy?.rulesId||o.cardId}/${k.id}`;return `<label class="detail-line" style="margin-top:8px">${h(k.label)}<select data-policy="${h(key)}" style="display:block;width:100%;margin:4px 0">${(k.provisioner?['ASK','Treasure','Food']:['ASK','YES','NO']).map(v=>`<option ${(g.state.optionalPreferences[key]||(k.provisioner?'Treasure':'ASK'))===v?'selected':''}>${v}</option>`).join('')}</select></label>`;}).join('')}</details>`;
}
