import { pairingMethods } from './pairing.js';
import { installExpandedEngine } from './expanded-core.js';
import { sequenceMethods } from './sequences.js';
import { Engine } from './engine.js';
import { actionMethods } from './actions.js';
import { zoneMethods } from './zones.js';
import { effectMethods } from './effects.js';
import { eventMethods } from './events.js';
import { phaseMethods } from './phases.js';
Object.assign(Engine.prototype, actionMethods, zoneMethods, effectMethods, eventMethods, phaseMethods, sequenceMethods, pairingMethods);
installExpandedEngine(Engine);
export { Engine };
export { CardRegistry } from './registry.js';
export { parseDeck, createGameState, validateState, makeInstance } from './deck.js';
export { RuleError, RULES_PACK, VERSION, COLORS, STEPS, ZONES, clone, ref, stateHash } from './util.js';
export { parseManaCost, manaCostText, suggestPayment } from './mana.js';
export { candidates, matches } from './selectors.js';
